/**
 * ==========================================
 * Deltamod Core Script
 * ==========================================
 */


// Global Variables & State
var audio = new Audio();
audio.preload = "none";
var currentAudio = "";
var currentAudioSource = "";
const menuAudioPositions = new Map();
var themeVideoSuspendTimer = null;
var suspendedThemeVideo = null;
var themeVideoLoadTimer = null;
var themeVideoFallbackActive = false;
var theme = null;
var pageN = null;
var addedStyle = null;
var currentPageScript = null;
var update = false;
var TARGET_MUSIC_VOLUME = 0.5;
var cmode = false; // Controller Mode
const MOTION = Object.freeze({
    fast: 140,
    standard: 180,
    easeOut: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1)'
});

function themeAssetUrl(themeConfig, folder, fileName) {
    if (themeConfig?.builtIn) {
        return window.deltamodBackend.assetUrl('app', `web/themes/${folder}/${fileName}`);
    }
    if (themeConfig?.runtimeLayout) {
        return window.deltamodBackend.assetUrl('theme', `${themeConfig.id}/${fileName}`);
    }
    return window.deltamodBackend.assetUrl('theme', `${folder}/${fileName}`);
}

function applyThemeStyles(themeConfig = theme) {
    const parsedThemeColor = window.ThemeSprites?.parseThemeColor(themeConfig.color)
        || [205, 68, 81];
    const [red, green, blue] = parsedThemeColor;
    const controlPalette = window.ThemeSprites?.controlPalette(parsedThemeColor) || {
        hoverColor: [213, 98, 109],
        inkColor: '#ffffff',
        hoverInkColor: '#000000'
    };
    const [hoverRed, hoverGreen, hoverBlue] = controlPalette.hoverColor;
    document.getElementById('dynamic-theme-styles').textContent = `
    /* Generated by Deltamod */
    :root {
        --theme-color: ${themeConfig.color};
        --theme-soul-color: ${themeConfig.soulColor || themeConfig.color};
        --theme-color-rgbaless: rgba(${red}, ${green}, ${blue}, 0.8);
        --theme-color-point2: rgba(${red}, ${green}, ${blue}, 0.2);
        --theme-color-point3: rgba(${red}, ${green}, ${blue}, 0.3);
        --theme-color-hover: rgb(${hoverRed}, ${hoverGreen}, ${hoverBlue});
        --theme-color-ink: ${controlPalette.inkColor};
        --theme-color-hover-ink: ${controlPalette.hoverInkColor};
    }
    input, select {
        box-shadow: inset 0 0 0 1px rgba(${red}, ${green}, ${blue}, 0.42);
    }
    input, progress {
        accent-color: ${themeConfig.color};
    }
    .sidebar {
        border-color: ${themeConfig.color};
    }
    ${themeConfig.specialCSS || ''}
    `;
}

function prefersReducedMotion() {
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

function releaseAudioBuffer() {
    rememberMenuAudioPosition();
    audio.pause();
    audio.currentTime = 0;
    audio.removeAttribute('src');
    audio.load();
    currentAudio = "";
    currentAudioSource = "";
}

function rememberMenuAudioPosition() {
    if (currentAudioSource && Number.isFinite(audio.currentTime)) {
        menuAudioPositions.set(currentAudioSource, audio.currentTime);
    }
}

function configureMenuAudioPlayback(source) {
    const themeSource = theme?.mainSong
        ? themeAssetUrl(theme, 'mus', theme.mainSong)
        : '';
    const isThemeTrack = source === themeSource;
    const configuredRate = isThemeTrack ? Number(theme?.musicPlaybackRate) : 1;
    const playbackRate = Number.isFinite(configuredRate)
        ? Math.min(2, Math.max(0.5, configuredRate))
        : 1;

    audio.defaultPlaybackRate = playbackRate;
    audio.playbackRate = playbackRate;
    if ('preservesPitch' in audio) {
        audio.preservesPitch = isThemeTrack
            ? theme?.musicPreservesPitch !== false
            : true;
    }
}

function switchMenuAudioSource(source) {
    rememberMenuAudioPosition();
    audio.pause();

    const resumeAt = menuAudioPositions.get(source) || 0;
    currentAudioSource = source;
    audio.src = source;
    configureMenuAudioPlayback(source);

    const restorePosition = () => {
        if (currentAudioSource !== source) return;

        const latestResumeAt = menuAudioPositions.get(source) || resumeAt;
        const maximumPosition = Number.isFinite(audio.duration)
            ? Math.max(0, audio.duration - 0.44)
            : latestResumeAt;
        audio.currentTime = Math.min(latestResumeAt, maximumPosition);
    };

    if (audio.readyState >= 1) {
        restorePosition();
    } else {
        audio.addEventListener('loadedmetadata', restorePosition, { once: true });
    }
}

function loopMenuAudio() {
    const loopBuffer = 0.44;
    if (Number.isFinite(audio.duration) && audio.currentTime > audio.duration - loopBuffer) {
        audio.currentTime = 0;
        audio.play().catch(() => {});
    }
}

audio.addEventListener('timeupdate', loopMenuAudio);

function themeUsesIntegratedVideoAudio(themeConfig = theme) {
    return Boolean(
        themeConfig?.backgroundVideo
        && themeConfig?.videoHasAudio
        && !themeVideoFallbackActive
    );
}

function getThemeBackgroundVideo() {
    return document.getElementById('theme-background-video');
}

function themeVideoUrl(themeConfig = theme) {
    if (!themeConfig?.backgroundVideo) return '';
    return themeAssetUrl(themeConfig, 'video', themeConfig.backgroundVideo);
}

function setThemeVideoAudioEnabled(enabled) {
    const video = getThemeBackgroundVideo();
    if (!video || !themeUsesIntegratedVideoAudio()) return;
    video.muted = !enabled;
    video.volume = enabled ? TARGET_MUSIC_VOLUME : 0;
    if (video.src && video.paused) {
        video.play().catch(() => {});
    }
}

function suspendThemeBackgroundVideo() {
    const video = getThemeBackgroundVideo();
    if (!video?.src || !theme?.backgroundVideo) return;

    suspendedThemeVideo = {
        source: video.dataset.source,
        currentTime: Number.isFinite(video.currentTime) ? video.currentTime : 0
    };
    video.pause();
    video.volume = 0;
}

function resumeThemeBackgroundVideo(audioEnabled) {
    const video = getThemeBackgroundVideo();
    const expectedSource = themeVideoUrl();
    if (!video || !suspendedThemeVideo || suspendedThemeVideo.source !== expectedSource) {
        return false;
    }

    const resumeAt = suspendedThemeVideo.currentTime;
    suspendedThemeVideo = null;
    video.muted = !audioEnabled;
    video.volume = audioEnabled ? TARGET_MUSIC_VOLUME : 0;

    const resumePlayback = () => {
        const maximumPosition = Number.isFinite(video.duration)
            ? Math.max(0, video.duration - 0.44)
            : resumeAt;
        const targetTime = Math.min(resumeAt, maximumPosition);
        if (Math.abs(video.currentTime - targetTime) > 0.05) {
            video.currentTime = targetTime;
        }
        video.play().catch(() => {});
    };

    if (video.readyState >= HTMLMediaElement.HAVE_METADATA) {
        resumePlayback();
    } else {
        video.addEventListener('loadedmetadata', resumePlayback, { once: true });
    }
    return true;
}

function scheduleThemeVideoSuspension() {
    clearTimeout(themeVideoSuspendTimer);
    const video = getThemeBackgroundVideo();
    if (video?.src) {
        suspendThemeBackgroundVideo();
    }
}

function applyThemeBackground() {
    const background = document.querySelector('.bg');
    const video = getThemeBackgroundVideo();
    if (!background || !video) return;

    background.style.backgroundImage = `url("${themeAssetUrl(theme, 'img', theme.background)}")`;
    if (!theme.backgroundVideo) {
        clearTimeout(themeVideoSuspendTimer);
        clearTimeout(themeVideoLoadTimer);
        suspendedThemeVideo = null;
        themeVideoFallbackActive = false;
        video.pause();
        video.hidden = true;
        video.removeAttribute('src');
        video.removeAttribute('poster');
        video.removeAttribute('data-source');
        video.load();
        return;
    }

    const source = themeVideoUrl();
    clearTimeout(themeVideoLoadTimer);
    themeVideoFallbackActive = false;
    video.poster = themeAssetUrl(theme, 'img', theme.background);
    video.hidden = true;
    video.loop = true;
    video.onplaying = () => {
        clearTimeout(themeVideoLoadTimer);
        video.hidden = false;
        background.style.backgroundImage = 'none';
    };
    video.onerror = () => {
        void fallBackFromThemeVideo(video, background, `media error ${video.error?.code || 'unknown'}`);
    };
    if (video.dataset.source !== source) {
        suspendedThemeVideo = null;
        video.muted = true;
        video.volume = 0;
        video.dataset.source = source;
        video.src = source;
    }
    video.play().catch(error => {
        void fallBackFromThemeVideo(video, background, error?.name || 'playback rejected');
    });
    const themeVideoReadyTimeout = window.DeltamodLinuxCompat?.isLinuxTauri
        && window.DeltamodLinuxCompat.getMode?.() === 'quality'
        ? 20000
        : 5000;
    themeVideoLoadTimer = setTimeout(() => {
        if (video.readyState < HTMLMediaElement.HAVE_FUTURE_DATA) {
            void fallBackFromThemeVideo(video, background, 'load timeout');
        }
    }, themeVideoReadyTimeout);
}

async function fallBackFromThemeVideo(video, background, reason) {
    if (themeVideoFallbackActive || video.dataset.source !== themeVideoUrl()) return;
    themeVideoFallbackActive = true;
    clearTimeout(themeVideoLoadTimer);
    video.pause();
    video.hidden = true;
    video.removeAttribute('src');
    video.removeAttribute('data-source');
    video.load();
    background.style.backgroundImage = `url("${themeAssetUrl(theme, 'img', theme.background)}")`;
    console.warn(`Theme video unavailable (${reason}); using poster and audio fallback.`);

    if (await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"])) {
        currentAudio = 'mainTheme.mp3';
        switchMenuAudioSource(themeAssetUrl(theme, 'mus', theme.mainSong));
        audio.loop = true;
        audio.volume = TARGET_MUSIC_VOLUME;
        await audio.play().catch(() => {});
    }
}

window._onClosePage = window._onClosePage || [];

const PAGE_STYLESHEET_OVERRIDES = Object.freeze({
    allmods: './views/main/main.css'
});

const PAGE_REGISTRY = Object.freeze(Object.fromEntries([
    'allmods',
    'collection-exportchoose',
    'collections',
    'credits',
    'deleteall',
    'gamebanana-browse',
    'gamebanana-leave-comment',
    'goc-dl',
    'installmanager',
    'locate',
    'main',
    'options',
    'patching',
    'themesel'
].map(name => [name, Object.freeze({
    name,
    html: `./views/${name}/index.html`,
    script: `./views/${name}/index.js`,
    base: `./views/${name}/`,
    stylesheet: PAGE_STYLESHEET_OVERRIDES[name] || null
})])));

const pageMarkupCache = new Map();

function loadPageMarkup(pageDefinition) {
    if (!pageMarkupCache.has(pageDefinition.html)) {
        const request = fetch(pageDefinition.html)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`Failed to load page ${pageDefinition.name}: HTTP ${response.status}`);
                }
                return response.text();
            })
            .catch(error => {
                pageMarkupCache.delete(pageDefinition.html);
                throw error;
            });
        pageMarkupCache.set(pageDefinition.html, request);
    }
    return pageMarkupCache.get(pageDefinition.html);
}

function warmPageMarkupCache() {
    for (const pageDefinition of Object.values(PAGE_REGISTRY)) {
        loadPageMarkup(pageDefinition).catch(error => {
            console.warn(`Unable to prepare page ${pageDefinition.name}:`, error);
        });
    }
}

function loadPageScript(pageDefinition) {
    if (currentPageScript) {
        currentPageScript.remove();
        currentPageScript = null;
    }

    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = pageDefinition.script;
        script.async = false;
        script.dataset.pageScript = pageDefinition.name;
        script.addEventListener('load', () => resolve(), { once: true });
        script.addEventListener(
            'error',
            () => reject(new Error(`Failed to load script for page: ${pageDefinition.name}`)),
            { once: true }
        );
        currentPageScript = script;
        document.body.appendChild(script);
    });
}

/**
 * Wrapper for invoking Electron IPC calls.
 */
async function invoke(...params) {
    return window.deltamodBackend.invoke(...params);
}

/**
 * Generates and appends glyph icons to the DOM.
 * @param {Array} jsonArr - Array of glyph objects { icon, description }
 */
async function makeGlyphs(jsonArr) {
    var glyphContainer = document.querySelector('.glyph');
    glyphContainer.innerHTML = '';
    
    jsonArr.forEach(glyph => {
        var glyphIconElement = document.createElement('span');
        glyphIconElement.classList.add('material-symbols-outlined');
        glyphIconElement.innerText = glyph.icon;

        var glyphDescElement = document.createElement('span');
        glyphDescElement.innerText = glyph.description;

        glyphContainer.appendChild(glyphIconElement);
        glyphContainer.appendChild(glyphDescElement);
    });
}

async function reapplyHAStyles() {
    var alignment = localStorage.getItem('alertAlignment') || 'Bottom';
    if (!localStorage.getItem('alertAlignment')) {
        localStorage.setItem('alertAlignment', alignment);
    }
    var haDynamicStyle = document.getElementById('haDynamicStyle');
    if (!haDynamicStyle) {
        haDynamicStyle = document.createElement('style');
        haDynamicStyle.id = 'haDynamicStyle';
        document.head.appendChild(haDynamicStyle);
    }
    haDynamicStyle.innerHTML = await fetch('./haAlignments/' + alignment + '.css').then(res => res.text());
}

/**
 * Prompts the user to leave Controller Mode.
 */
async function promptLeaveCMode() {
    htmlAlert(
        "Exit controller mode", 
        "Are you sure you want to exit controller mode? If you exit controller mode, Deltamod will close.", 
        [
            { text: "Yes", resolveWith: true },
            { text: "No", resolveWith: false }
        ], 
        'stadia_controller'
    ).then(async (result) => {
        if (result) {
            await window.deltamodBackend.invoke('cmode-off', []);
        }
    });
}

/**
 * Plays the "rew" SFX.
 */
async function rew() {
    if (await window.deltamodBackend.invoke('getUniqueFlag', ["SFX"]) === false) {
        return;
    }
    var a = new Audio();
    a.src = 'audio/rew.mp3';
    a.play();
}

/**
 * Brightens an RGB color by a specified amount.
 */
function brightenColor(r, g, b, amount) {
    r = Math.min(255, r + amount);
    g = Math.min(255, g + amount);
    b = Math.min(255, b + amount);
    return `rgb(${r}, ${g}, ${b})`;
}

// Window Management
function toggleFullscreen() { window.deltamodBackend.invoke('toggleFullscreen', []); }
function toggleMinimize() { window.deltamodBackend.invoke('minimizeMe', []); }
function closeCommunity() {
    window.deltamodBackend.invoke('quitCommunityForEasterEgg', []).catch(() => window.close());
}
function genbtnstyles() { /* deprecated */ }

// Play rewind SFX on specific preload trigger
window.preloadAPI.onWRA(() => rew());

function error() {
    fetch('http://google.com'); // Force an error trigger if used in a specific context
}

function disableElem(elem) {
    if (!elem) return;
    elem.style.pointerEvents = 'none';
    elem.style.opacity = '0';
}
function enableElem(elem) {
    if (!elem) return;
    elem.style.pointerEvents = 'auto';
    elem.style.opacity = '1';
}

/**
 * ==========================================
 * Custom HTML Alert System
 * ==========================================
 */
var alertCache = [];
var isAlertShowing = false;

/**
 * Queues or displays an HTML-based alert dialog.
 */
async function htmlAlert(title, message, buttons, specialIcon) {
    if (isAlertShowing) {
        return new Promise((resolve, reject) => {
            alertCache.push({ title, message, buttons, resolve, reject, specialIcon: 'info' });
        });
    } else {
        return htmlAlertRaw(title, message, buttons, specialIcon);
    }
}

/**
 * Internal function to handle the rendering of the HTML alert.
 */
async function htmlAlertRaw(title, message, buttons, specialIcon = 'info') {
    return new Promise(async (resolve, reject) => {
        isAlertShowing = true;

        if (
            localStorage.getItem('alertAlignment') == "Separate"
            && window.deltamodBackend.isCommandAvailable('htmlAlert_outwin')
        ) {
            var index = await window.deltamodBackend.invoke('htmlAlert_outwin', [title, message, buttons]);
            isAlertShowing = false;
            var button = buttons[index];

            if (button.resolveWith) {
                resolve(button.resolveWith);
                return;
            }

            if (button.rejectWith) {
                reject(button.rejectWith);
                return;
            }

            return;
        }

        var alertMain = document.getElementsByClassName('alertMain')[0];
        var alertMsgR = alertMain.getElementsByClassName('alertMsg')[0];

        const animationDuration = prefersReducedMotion() ? 0 : MOTION.standard;
        const animationSeconds = animationDuration / 1000;
        const animOptions = `${MOTION.easeOut} forwards`;

        alertMsgR.innerHTML = '';

        // Container
        var alertMsg = document.createElement('div');
        alertMsgR.appendChild(alertMsg);

        // Title
        var titleElement = document.createElement('h1');
        titleElement.innerText = title;
        titleElement.style.opacity = '1';
        
        // Message
        var messageElement = document.createElement('p');
        messageElement.textContent = String(message);
        messageElement.style.whiteSpace = 'pre-line';
        messageElement.style.opacity = '1';
        
        alertMsg.appendChild(titleElement);
        alertMsg.appendChild(messageElement);

        // Buttons
        var buttonsHTML = document.createElement('div');
        buttonsHTML.style.textAlign = 'right';
        buttonsHTML.classList.add('alertButtons');
        buttonsHTML.style.opacity = '1';
        buttonsHTML.style.display = 'flex';
        buttonsHTML.style.gap = '8px';
        buttonsHTML.style.justifyContent = 'flex-end';
        

        buttons.forEach((button) => {
            var btn = document.createElement('button');
            btn.textContent = button.text;
            btn.style.flex = '1 1 0';
            btn.onclick = async function() {
                buttonsHTML.style.pointerEvents = 'none';
                // Outro animation
                alertMsgR.style.animation = animationDuration === 0
                    ? 'none'
                    : `${animationSeconds}s alertFadeOut ${MOTION.easeIn} forwards`;
                setTimeout(() => {
                    alertMain.style.animation = '';
                    alertMain.style.display = 'none';
                    alertMain.hidden = true;
                    alertMsgR.style.animation = 'none';
                    alertMsgR.innerHTML = '';
                }, animationDuration);
                
                isAlertShowing = false;
                
                // Play dismiss SFX
                var a = new Audio();
                a.src = 'audio/booow.mp3';
                if (await window.deltamodBackend.invoke('getUniqueFlag', ["SFX"]) === true) {
                    a.play().catch(() => {});
                }

                // Resolve/Reject
                if (button.resolveWith) {
                    resolve(button.resolveWith);
                    return;
                }
                if (button.rejectWith) {
                    reject(button.rejectWith);
                    return;
                }
                if (button.onClick) button.onClick();

                // Process next alert in cache
                if (alertCache.length > 0) {
                    setTimeout(() => {
                        var nextAlert = alertCache.shift();
                        htmlAlertRaw(nextAlert.title, nextAlert.message, nextAlert.buttons)
                            .then(nextAlert.resolve)
                            .catch(nextAlert.reject);
                    }, animationDuration);
                }
            };
            buttonsHTML.appendChild(btn);
        });

        alertMain.hidden = false;
        alertMain.style.display = 'flex';
        alertMsg.appendChild(buttonsHTML);
        alertMsgR.style.animation = 'none';
        void alertMsgR.offsetWidth;
        alertMsgR.style.animation = animationDuration === 0
            ? 'none'
            : `${animationSeconds}s alertFadeIn ${animOptions}`;

        // Special Background Icon
        var bigIcon = document.createElement('span');
        bigIcon.classList.add('material-symbols-outlined', 'alertBigIcon');
        bigIcon.innerText = specialIcon;
        bigIcon.style.fontSize = '490px';
        bigIcon.style.position = 'absolute';
        bigIcon.style.top = '-140px';
        bigIcon.style.right = '-50px';
        bigIcon.style.opacity = '0.1';
        bigIcon.style.userSelect = 'none';
        bigIcon.style.pointerEvents = 'none';
        alertMsgR.appendChild(bigIcon);

        // Play alert SFX
        var a = new Audio();
        a.src = 'audio/htmlalert.mp3';
        a.playbackRate = 0.9;
        if (await window.deltamodBackend.invoke('getUniqueFlag', ["SFX"]) === true) {
            a.play();
        }
    });
}

function credits(funny) {
    page('credits');
}

/**
 * ==========================================
 * Preload API Listeners (Updates, Logging)
 * ==========================================
 */
window.preloadAPI.onUpdateAvailable((info) => {
    console.log('Update available:', info.version);
    update = true;
    window.ustack = {};
    window.ustack.updateInfo = info;

    htmlAlert(
        'Update available', 
        `A new version of Deltamod Community (${info.version}) is available for download. Do you wish to update?`,
        [
            { text: 'Yes', resolveWith: "a" },
            { text: 'No', rejectWith: "a" }
        ], 
        'update'
    ).then(async () => {
        await window.deltamodBackend.invokeOptional('start-update', [], false);
    }).catch(async () => {
        await window.deltamodBackend.invokeOptional('ignore-update', [], false);
    });
});

window.preloadAPI.onDLMODProgress((info) => window.currentPageStack.dlmod && window.currentPageStack.dlmod(info));
window.preloadAPI.onDDS((info) => window.currentPageStack.du && window.currentPageStack.du(info.percentage));
window.preloadAPI.onProtocolDownloadProgress((info) => window.currentPageStack.onDLP && window.currentPageStack.onDLP(info.percentage));
window.preloadAPI.onProfileImportProgress((info) => window.currentPageStack.profileImportProgress && window.currentPageStack.profileImportProgress(info));
window.preloadAPI.onHashProgress((info) => window.currentPageStack.hashProgress && window.currentPageStack.hashProgress(info));
window.preloadAPI.onRefresh(() => page(pageN));
window.preloadAPI.onUpdateProgress((info) => window.currentPageStack.u && window.currentPageStack.u(info.perc));
window.preloadAPI.onFinishedPatch(() => window.currentPageStack.fp && window.currentPageStack.fp());
window.preloadAPI.onGPL((message) => window.currentPageStack.gpl && window.currentPageStack.gpl(message));
window.preloadAPI.onPage((title) => page(title));
window.preloadAPI.onAudio((stat) => stat ? openAudio() : closeAudio());
window.preloadAPI.onLeaveControllerMode(() => promptLeaveCMode());

function sanitizeHTML(str) {
    var temp = document.createElement('div');
    temp.textContent = str;
    return temp.innerHTML;
}

function formatBytes(bytes) {
    if (!Number.isFinite(bytes) || bytes < 0) return 'an unknown amount of space';
    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    let value = bytes;
    let unit = 0;
    while (value >= 1024 && unit < units.length - 1) {
        value /= 1024;
        unit += 1;
    }
    return `${value.toFixed(unit === 0 ? 0 : 1)} ${units[unit]}`;
}

async function offerOfficialProfileImport() {
    try {
        const summary = await window.communityAPI.profile.summary();
        if (!summary.exists || summary.previousImport || localStorage.getItem('communityMigrationPromptDismissed') === 'true') {
            return false;
        }

        const choice = await htmlAlert(
            'Import your Deltamod data',
            `Deltamod ${summary.version || ''} was found with ${summary.installations} installation(s), ${summary.mods} mod(s), and ${summary.themes} custom theme(s). A safe Community copy needs ${formatBytes(summary.totalBytes)}. Official Deltamod will not be changed.`,
            [
                { text: 'Review and import', resolveWith: 'import' },
                { text: 'Later', resolveWith: 'later' }
            ],
            'database'
        );

        if (choice === 'import') {
            window._pageArguments = { cat: 'data' };
            await page('options');
            return true;
        }

        localStorage.setItem('communityMigrationPromptDismissed', 'true');
    } catch (error) {
        console.warn('Could not inspect the official Deltamod profile:', error.message || error);
    }
    return false;
}

// Override console methods to tunnel logs through Electron IPC
console.log = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'LOG', pageN]); };
console.warn = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'WARN', pageN]); };
console.error = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'ERROR', pageN]); };
console.info = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'INFO', pageN]); };

function uppercaseFirst(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

function adaptForIcons(element) {
    element.style.display = 'flex';
    element.style.alignItems = 'left';
    element.style.gap = '5px';
    element.style.justifyContent = 'left';
    return element;
}

function icon(name, fontSize) {
    return `<span class="material-symbols-outlined" style="font-size: ${fontSize}">${name}</span>`;
}

async function invokeOptional(channel, data, fallback) {
    return window.deltamodBackend.invokeOptional(channel, data, fallback);
}

// The React boot overlay is optional so the vanilla renderer remains usable if
// a development build is missing the generated bundle. These helpers also keep
// loading milestones in one place instead of coupling page code to React.
function bootProgress(progress, status) {
    window.DeltamodBoot?.setProgress(progress, status);
}

function bootTheme(themeConfig) {
    if (!themeConfig) return;
    window.DeltamodBoot?.setTheme({
        themeColor: themeConfig.color,
        soulColor: themeConfig.soulColor || themeConfig.color,
        backgroundImage: themeConfig.background
            ? themeAssetUrl(themeConfig, 'img', themeConfig.background)
            : undefined,
        backgroundVideo: themeConfig.backgroundVideo ? themeVideoUrl(themeConfig) : undefined,
        readyAtVideoTime: Number.isFinite(themeConfig.bootSyncTime)
            ? themeConfig.bootSyncTime
            : undefined,
    });
}

function finishBoot() {
    window.DeltamodBoot?.finish();
}

/**
 * ==========================================
 * Theme & Audio Rendering
 * ==========================================
 */

/**
 * Refreshes the application theme and applies background/music.
 * @param {boolean} refreshAudio - Whether to also reload and play the main theme song.
 */
async function themeRefresh(refreshAudio = true) {
    const themeName = await window.deltamodBackend.invoke('getTheme', []);
    const themePath = `data/${themeName}.theme.json`;
    let response;
    let builtIn = false;
    let runtimeLayout = false;
    try {
        response = await fetch(window.deltamodBackend.assetUrl('theme', themePath));
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
    } catch (error) {
        try {
            response = await fetch(window.deltamodBackend.assetUrl('theme', `${themeName}/theme.json`));
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            runtimeLayout = true;
        } catch {
            response = await fetch(window.deltamodBackend.assetUrl('app', `web/themes/${themePath}`));
            if (!response.ok) throw error;
            builtIn = true;
        }
    }
    theme = await response.json();
    theme.builtIn = builtIn;
    theme.runtimeLayout = runtimeLayout;
    if (runtimeLayout) {
        theme.background = theme.background || theme.icon;
        theme.mainSong = theme.mainSong || theme.music;
        theme.description = theme.description || 'Custom theme';
        theme.musicTrack = theme.musicTrack || (theme.mainSong ? 'Custom audio' : 'No custom audio');
        theme.color = theme.color || 'rgb(205, 68, 81)';
        theme.soulColor = theme.soulColor || '#FF0000';
    }
    bootTheme(theme);
    applyThemeBackground();
    applyThemeStyles(theme);
    // The seasonal layer stays hidden until these CSS variables contain the
    // active theme, preventing a default-color flash during startup or swaps.
    window.SeasonalEvents?.setThemeReady(true);
    window.ThemeSprites?.apply(theme.soulColor || theme.color, document).catch(error => {
        console.warn('Unable to recolor theme sprites:', error);
    });
    window.ThemeSprites?.applyAppIcon(theme, window.deltamodBackend).catch(error => {
        console.warn('Unable to update the themed application icon:', error);
    });
    
    if (refreshAudio) {
        const shouldPlayAudio = await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"]);
        if (themeUsesIntegratedVideoAudio()) {
            releaseAudioBuffer();
            setThemeVideoAudioEnabled(shouldPlayAudio);
        } else if (shouldPlayAudio && theme.mainSong) {
            audio.loop = true;
            audio.volume = TARGET_MUSIC_VOLUME;
            currentAudio = 'mainTheme.mp3';
            switchMenuAudioSource(themeAssetUrl(theme, 'mus', theme.mainSong));
            await audio.play().catch(() => {});
        } else {
            releaseAudioBuffer();
        }
    }
}

window.preloadAPI.onThemeChange(themeRefresh);
window.ThemeSprites?.observe(() => theme?.soulColor || theme?.color);

let lockRandoms = false;

function elisten(element, event, handler) {
    element.addEventListener(event, handler);
    window._eventListeners = window._eventListeners || [];
    window._eventListeners.push({ element, event, handler });
}

/**
 * Navigates to a specific internal page and processes HTML/CSS injections.
 * @param {string} name - The identifier of the page to load.
 */
let activePageNavigation = null;
let queuedPageNavigation = null;
let pageNavigationDrain = null;

function page(name) {
    const forceReload = name === '';
    const target = forceReload ? pageN : name;

    if (!target) {
        return Promise.resolve(false);
    }

    if (!forceReload && (
        target === activePageNavigation ||
        target === queuedPageNavigation?.target
    )) {
        return Promise.resolve(false);
    }

    const navigation = new Promise((resolve, reject) => {
        if (queuedPageNavigation) {
            queuedPageNavigation.resolve(false);
        }
        queuedPageNavigation = { target, resolve, reject };
    });

    schedulePageNavigationDrain();

    return navigation;
}

function schedulePageNavigationDrain() {
    if (pageNavigationDrain) return;

    pageNavigationDrain = drainPageNavigations().finally(() => {
        pageNavigationDrain = null;
        if (queuedPageNavigation) {
            schedulePageNavigationDrain();
        }
    });
}

async function drainPageNavigations() {
    while (queuedPageNavigation) {
        const navigation = queuedPageNavigation;
        queuedPageNavigation = null;
        activePageNavigation = navigation.target;

        try {
            await renderPage(navigation.target);
            navigation.resolve(true);
        } catch (error) {
            navigation.reject(error);
        } finally {
            activePageNavigation = null;
        }
    }
}

async function renderPage(name) {
    rew();

    // Clear existing intervals/listeners to prevent memory leaks
    try {
        window._intervals.forEach(clearInterval);
    } catch(e) {
        console.log('No intervals to clear');
    }
    window._intervals = [];

    window._eventListeners = window._eventListeners || [];
    window._eventListeners.forEach(({ element, event, handler }) => {
        element.removeEventListener(event, handler);
    });
    window._eventListeners = [];

    window._onClosePage = window._onClosePage || [];
    window._onClosePage.forEach(func => func());
    window._onClosePage = [];

    if (currentPageScript) {
        currentPageScript.remove();
        currentPageScript = null;
    }

    if (addedStyle) {
        addedStyle.remove();
        addedStyle = null;
    }
    
    if (name == "") {
        name = pageN;
    }

    // Prevents escaping to home if game is baked
    if (name === 'main' && PAGE_REGISTRY.bakedhome && await window.deltamodBackend.invoke('isBaked', [])) {
        name = 'bakedhome';
    }
    const pageDefinition = PAGE_REGISTRY[name];
    if (!pageDefinition) {
        throw new Error(`Blocked unknown page: ${String(name)}`);
    }

    // Keep navigation immediate. Animating the full viewport promotes every
    // blurred panel to a large compositor surface and retains substantial GPU
    // memory after each page change.
    const viewport = document.querySelector('.viewport');
    viewport.style.animation = 'none';
    window.deltamodBackend.invoke('showWindow', []);

    // Load theme if not yet initialized
    if (!theme) {
        await themeRefresh(false); 
    }

    window.currentPageStack = {};

    // Process Page HTML
    var purifiedHTML = await loadPageMarkup(pageDefinition);
    await window.Localization?.ready;
    purifiedHTML = window.Localization?.replaceTokens(purifiedHTML) || purifiedHTML;
    
    var runScripts = false;
    var changeAudio = false;

    // Detect and queue JS execution
    if (purifiedHTML.includes('JSL')) {
        purifiedHTML = purifiedHTML.replace('JSL', '');
        runScripts = true;
    }

    // Load internal stylesheet tags
    if (purifiedHTML.includes('STYLESHEET[')) {
        var stylesheetSrc = purifiedHTML.match(/STYLESHEET\[(.*?)\]/);
        if (stylesheetSrc && stylesheetSrc[1]) {
            if (addedStyle) addedStyle.remove();
            addedStyle = document.createElement('link');
            addedStyle.rel = 'stylesheet';
            addedStyle.dataset.pageStylesheet = name;
            if (pageDefinition.stylesheet) {
                addedStyle.href = pageDefinition.stylesheet;
            } else {
                if (!/^[a-z0-9_-]+$/i.test(stylesheetSrc[1])) {
                    throw new Error(`Blocked unsafe stylesheet name on page ${name}.`);
                }
                addedStyle.href = `${pageDefinition.base}${stylesheetSrc[1]}.css`;
            }
            document.getElementById('head').appendChild(addedStyle);
        }
        purifiedHTML = purifiedHTML.replace(/STYLESHEET\[(.*?)\]/g, '');
    } else if (addedStyle) {
        addedStyle.remove();
        addedStyle = null;
    }

    // Handle NO-SIDEBAR tag
    if (purifiedHTML.includes('NO-SIDEBAR')) {
        purifiedHTML = purifiedHTML.replace('NO-SIDEBAR', '');
        ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => button.setAttribute('data-disabled', 'true'));
    } else {
        ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => button.setAttribute('data-disabled', 'false'));
    }

    // Extract Title Tag
    var title = purifiedHTML.match(/TITLE\[(.*?)\]/);
    purifiedHTML = purifiedHTML.replace(/TITLE\[(.*?)\]/g, '');
    const pageTitle = window.Localization?.translateKnownText(
        title?.[1] || 'Deltamod Community'
    ) || title?.[1] || 'Deltamod Community';
    const pageTitleElement = document.getElementById('pageTitle');
    if (pageTitleElement) {
        pageTitleElement.textContent = pageTitle;
    }

    // Extract Exclude Audio Tag
    var themeAudioExclude = purifiedHTML.match(/THEME-AUDIO-EXCLUDE\[(.*?)\]/);
    purifiedHTML = purifiedHTML.replace(/THEME-AUDIO-EXCLUDE\[(.*?)\]/g, '');

    // Process Audio Tag
    if (true) {
        var audioSrc = purifiedHTML.match(/AUDIO\[(.*?)\]/);
        console.log('Audio source found:' + audioSrc);
        
        if (!audioSrc || !audioSrc[1]) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }
        if (theme.id == themeAudioExclude?.[1]) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }
        const [dynamicMusic, shouldPlayAudio] = await Promise.all([
            window.deltamodBackend.invoke('getUniqueFlag', ["DYNAMUSIC"]),
            window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"])
        ]);
        if (dynamicMusic == false) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }

        if (themeUsesIntegratedVideoAudio()) {
            releaseAudioBuffer();
            setThemeVideoAudioEnabled(shouldPlayAudio);
        } else if (!shouldPlayAudio) {
            releaseAudioBuffer();
        } else if (audioSrc?.[1] === 'mainTheme.mp3' && !theme.mainSong) {
            releaseAudioBuffer();
        } else if (audioSrc && audioSrc[1] && (audioSrc[1] !== currentAudio || !audio.src)) {
            currentAudio = audioSrc[1];
            const nextAudioSource = audioSrc[1] == 'mainTheme.mp3'
                ? themeAssetUrl(theme, 'mus', theme.mainSong)
                : './' + audioSrc[1];
            switchMenuAudioSource(nextAudioSource);

            audio.volume = TARGET_MUSIC_VOLUME;
            changeAudio = true;
        }

        if (shouldPlayAudio && !themeUsesIntegratedVideoAudio()) {
            audio.play().catch(() => {});
        }
        purifiedHTML = purifiedHTML.replace(/AUDIO\[(.*?)\]/g, '');
    }

    // Inject Viewport HTML
    const pageViewport = document.getElementsByClassName('viewport')[0];
    pageViewport.querySelectorAll('img, video, source').forEach(media => {
        media.removeAttribute('src');
        media.removeAttribute('srcset');
    });
    pageViewport.innerHTML = purifiedHTML;
    window.Localization?.apply(pageViewport);
    window.Localization?.applyKnownText(pageViewport);

    // Set Active Sidebar Button
    ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => {
        if (button.getAttribute('data-page') === name) {
            button.classList.add('active');
            button.setAttribute('aria-current', 'page');
        } else {
            button.classList.remove('active');
            button.removeAttribute('aria-current');
        }
    });

    // Handle Scrolling
    try {
        const vp = document.getElementsByClassName('viewport')[0];
        if (vp && typeof vp.scrollTo === 'function') {
            vp.scrollTo({ top: 0, left: 0, behavior: 'auto' });
        } else {
            window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
        }
    } catch (e) {
        window.scrollTo(0, 0);
    }

    pageN = name;

    applyThemeStyles(theme);

    // Execute Page JS
    if (runScripts) {
        try {
            await loadPageScript(pageDefinition);
        } catch (error) {
            console.error('Error occurred while loading script for page:', name, error);
        }
    }

    window.Localization?.apply(pageViewport);

    window.ThemeSprites?.apply(theme.soulColor || theme.color, document).catch(error => {
        console.warn('Unable to recolor page sprites:', error);
    });

}

/**
 * ==========================================
 * Global Window Listeners
 * ==========================================
 */
window.addEventListener('blur', () => {
    document.documentElement.classList.add('window-inactive');
    if (audio) {
        audio.volume = 0;
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo) {
        themeVideo.volume = 0;
    }
    scheduleThemeVideoSuspension();
});

window.addEventListener('focus', async () => {
    clearTimeout(themeVideoSuspendTimer);
    document.documentElement.classList.remove('window-inactive');
    let shouldPlayAudio = await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"]);
    if (audio && shouldPlayAudio) {
        audio.volume = TARGET_MUSIC_VOLUME;
    }
    const resumedThemeVideo = resumeThemeBackgroundVideo(shouldPlayAudio);
    if (!resumedThemeVideo) {
        setThemeVideoAudioEnabled(shouldPlayAudio);
    }
});

if (!window.electronAPI) {
    window.alert('This application cannot run in this environment.');
    window.close();
    window.location.href = 'about:blank';
}

var renderedUser = false;
async function renderuser() {
    if (!(await window.deltamodBackend.invoke('validateGamebananaToken')) || !navigator.onLine) {
        renderedUser = true;
        return;
    }
    var gbuser = await window.deltamodBackend.invokeOptional(
        'getGamebananaUserinfo',
        [],
        { loggedIn: false }
    );

    var gbaccount = document.querySelector('.gamebanana-account');
    gbaccount.replaceChildren();
    const avatar = document.createElement('img');
    const fallback = document.createElement('span');
    fallback.className = 'material-symbols-outlined gamebanana-account-fallback';
    fallback.textContent = 'account_circle';
    fallback.setAttribute('aria-hidden', 'true');
    const avatarUrl = typeof gbuser?._sAvatarUrl === 'string' ? gbuser._sAvatarUrl.trim() : '';
    avatar.src = avatarUrl;
    avatar.alt = '';
    avatar.width = 25;
    avatar.height = 25;
    avatar.style.borderRadius = '15px';
    avatar.onerror = () => {
        avatar.remove();
        if (!fallback.isConnected) gbaccount.prepend(fallback);
    };
    const username = document.createElement('span');
    username.textContent = String(gbuser?._sName || 'GameBanana user');
    username.className = 'gamebanana-account-name';
    if (avatarUrl) {
        gbaccount.append(avatar, username);
    } else {
        gbaccount.append(fallback, username);
    }
    gbaccount.style.opacity = '1';
    const openGameBananaSettings = async () => {
        if (gbaccount.getAttribute('data-disabled') === 'true') {
            return;
        }
        window._pageArguments = {
            cat: 'gb'
        };
        page('options');
    };
    gbaccount.addEventListener('click', openGameBananaSettings);
    gbaccount.addEventListener('keydown', event => {
        if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            openGameBananaSettings();
        }
    });

    renderedUser = true;
}

async function setupLanguageWheel() {
    await window.Localization.ready;

    const toggle = document.getElementById('language-wheel-toggle');
    const toggleFlag = document.getElementById('language-wheel-toggle-flag');
    const wheel = document.getElementById('language-wheel');
    const backdrop = document.getElementById('language-wheel-backdrop');
    const sectors = document.getElementById('language-wheel-sectors');
    const options = document.getElementById('language-wheel-options');
    const currentFlag = document.getElementById('language-wheel-current-flag');
    const languages = await window.Localization.getLanguages();
    const optionButtons = [];
    const sectorPaths = [];
    const wheelFlagCodes = Object.freeze({
        en: 'en',
        it: 'it',
        pl: 'pl',
        es: 'es',
        fr: 'fr',
        de: 'de',
        'pt-br': 'br',
        ja: 'jp'
    });
    const svgNamespace = 'http://www.w3.org/2000/svg';
    const sectorDefinitions = document.createElementNS(svgNamespace, 'defs');
    sectors.appendChild(sectorDefinitions);
    let closeTimer = null;
    let isChangingLanguage = false;
    let previewRotation = null;

    const selectedLanguage = () => (
        languages.find(language => language.code === window.Localization.getLanguage())
        || languages[0]
    );

    const wheelFlag = language => (
        `assets/language-flags/${wheelFlagCodes[language.code]}.svg`
    );

    const previewLanguage = language => {
        const previewIndex = Math.max(0, languages.findIndex(item => item.code === language.code));
        const targetRotation = previewIndex * (360 / languages.length);
        if (previewRotation === null) {
            previewRotation = targetRotation;
        } else {
            const currentNormalized = ((previewRotation % 360) + 360) % 360;
            const shortestDelta = (
                ((targetRotation - currentNormalized + 540) % 360) - 180
            );
            previewRotation += shortestDelta;
        }
        currentFlag.src = wheelFlag(language);
        currentFlag.alt = '';
        wheel.style.setProperty('--preview-angle', `${previewRotation}deg`);
        optionButtons.forEach(button => {
            button.classList.toggle('is-preview', button.dataset.language === language.code);
        });
        sectorPaths.forEach(path => {
            path.classList.toggle('is-preview', path.dataset.language === language.code);
        });
    };

    const syncLanguageWheel = () => {
        const language = selectedLanguage();
        toggleFlag.src = wheelFlag(language);
        previewLanguage(language);

        const changeLabel = window.Localization.t('language_switcher_label', 'Change language');
        toggle.title = changeLabel;
        toggle.setAttribute('aria-label', `${changeLabel}: ${language.name}`);
        wheel.setAttribute('aria-label', changeLabel);
        for (const button of optionButtons) {
            button.setAttribute(
                'aria-pressed',
                String(button.dataset.language === language.code)
            );
        }
        sectorPaths.forEach(path => {
            path.classList.toggle('is-current', path.dataset.language === language.code);
        });
    };

    const closeWheel = ({ returnFocus = true, restorePreview = true } = {}) => {
        if (wheel.hidden) return;
        clearTimeout(closeTimer);
        wheel.classList.remove('is-open');
        backdrop.classList.remove('is-open');
        wheel.setAttribute('aria-hidden', 'true');
        toggle.setAttribute('aria-expanded', 'false');

        const finishClose = () => {
            wheel.hidden = true;
            backdrop.hidden = true;
            if (restorePreview) previewLanguage(selectedLanguage());
            if (returnFocus) toggle.focus();
        };

        if (prefersReducedMotion()) {
            finishClose();
        } else {
            closeTimer = setTimeout(finishClose, 230);
        }
    };

    const openWheel = () => {
        clearTimeout(closeTimer);
        wheel.hidden = false;
        backdrop.hidden = false;
        wheel.setAttribute('aria-hidden', 'false');
        toggle.setAttribute('aria-expanded', 'true');
        syncLanguageWheel();

        requestAnimationFrame(() => {
            wheel.classList.add('is-open');
            backdrop.classList.add('is-open');
            const active = optionButtons.find(button => button.getAttribute('aria-pressed') === 'true');
            (active || optionButtons[0])?.focus();
        });
    };

    const focusRelativeOption = (button, direction) => {
        const currentIndex = optionButtons.indexOf(button);
        const nextIndex = (currentIndex + direction + optionButtons.length) % optionButtons.length;
        optionButtons[nextIndex].focus();
    };

    const activateLanguage = async language => {
        if (isChangingLanguage) return;
        if (language.code === window.Localization.getLanguage()) {
            closeWheel();
            return;
        }

        isChangingLanguage = true;
        previewLanguage(language);
        closeWheel({ returnFocus: false, restorePreview: false });
        try {
            await window.Localization.setLanguage(language.code);
            syncLanguageWheel();
            toggle.focus();
        } catch (error) {
            console.error(`Unable to switch language to ${language.code}:`, error);
            openWheel();
        } finally {
            isChangingLanguage = false;
        }
    };

    const polarPoint = (radius, angle) => {
        const radians = angle * (Math.PI / 180);
        return {
            x: 165 + (Math.cos(radians) * radius),
            y: 165 + (Math.sin(radians) * radius)
        };
    };

    const sectorPath = (startAngle, endAngle) => {
        const outerStart = polarPoint(157, startAngle);
        const outerEnd = polarPoint(157, endAngle);
        const innerEnd = polarPoint(68, endAngle);
        const innerStart = polarPoint(68, startAngle);
        return [
            `M ${outerStart.x} ${outerStart.y}`,
            `A 157 157 0 0 1 ${outerEnd.x} ${outerEnd.y}`,
            `L ${innerEnd.x} ${innerEnd.y}`,
            `A 68 68 0 0 0 ${innerStart.x} ${innerStart.y}`,
            'Z'
        ].join(' ');
    };

    languages.forEach((language, index) => {
        const button = document.createElement('button');
        const angle = index * (360 / languages.length);
        const buttonRadius = 112;
        const buttonAngle = (angle - 90) * (Math.PI / 180);
        const sector = document.createElementNS(svgNamespace, 'path');
        const pattern = document.createElementNS(svgNamespace, 'pattern');
        const patternImage = document.createElementNS(svgNamespace, 'image');
        const patternId = `language-sector-${language.code.replace(/[^a-z0-9]/gi, '-')}`;

        button.type = 'button';
        button.className = 'language-wheel-option noScaleBTN';
        button.dataset.language = language.code;
        button.title = language.name;
        button.setAttribute('aria-label', language.name);
        button.style.setProperty('--wheel-index', String(index));
        button.style.setProperty('--wheel-button-x', `${125 + (Math.cos(buttonAngle) * buttonRadius)}px`);
        button.style.setProperty('--wheel-button-y', `${123 + (Math.sin(buttonAngle) * buttonRadius)}px`);

        sector.classList.add('language-wheel-sector');
        sector.dataset.language = language.code;
        sector.style.fill = `url(#${patternId})`;
        sector.setAttribute('d', sectorPath(
            -112.5 + angle + 1.4,
            -67.5 + angle - 1.4
        ));

        pattern.id = patternId;
        pattern.setAttribute('width', '1');
        pattern.setAttribute('height', '1');
        pattern.setAttribute('patternUnits', 'objectBoundingBox');
        pattern.setAttribute('patternContentUnits', 'objectBoundingBox');
        patternImage.setAttribute('href', wheelFlag(language));
        patternImage.setAttribute('width', '1');
        patternImage.setAttribute('height', '1');
        patternImage.setAttribute('preserveAspectRatio', 'xMidYMid slice');
        pattern.appendChild(patternImage);
        sectorDefinitions.appendChild(pattern);
        sectors.appendChild(sector);
        sectorPaths.push(sector);

        sector.addEventListener('pointerover', () => {
            if (!isChangingLanguage) previewLanguage(language);
        });
        sector.addEventListener('click', () => activateLanguage(language));
        button.addEventListener('focus', () => previewLanguage(language));
        button.addEventListener('click', () => activateLanguage(language));
        button.addEventListener('keydown', event => {
            if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
                event.preventDefault();
                focusRelativeOption(button, 1);
            } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
                event.preventDefault();
                focusRelativeOption(button, -1);
            } else if (event.key === 'Home') {
                event.preventDefault();
                optionButtons[0].focus();
            } else if (event.key === 'End') {
                event.preventDefault();
                optionButtons[optionButtons.length - 1].focus();
            } else if (event.key === 'Escape') {
                event.preventDefault();
                closeWheel();
            }
        });

        optionButtons.push(button);
        options.appendChild(button);
    });

    toggle.addEventListener('click', () => {
        if (toggle.getAttribute('aria-expanded') === 'true') closeWheel();
        else openWheel();
    });
    wheel.addEventListener('pointerleave', () => {
        if (!isChangingLanguage) previewLanguage(selectedLanguage());
    });
    backdrop.addEventListener('click', () => closeWheel());
    window.addEventListener('keydown', event => {
        if (event.key === 'Escape' && !wheel.hidden) {
            event.preventDefault();
            closeWheel();
        }
    });
    window.addEventListener('deltamod-language-change', syncLanguageWheel);

    syncLanguageWheel();
}

/**
 * ==========================================
 * Initialization Boot Sequence
 * ==========================================
 */
(async function() {
    bootProgress(0.03, 'Starting local runtime');
    await reapplyHAStyles();
    bootProgress(0.09, 'Loading interface styles');

    cmode = await window.deltamodBackend.invoke('isCMode', []);
    bootProgress(0.15, 'Checking controller mode');

    var ribbon = document.querySelectorAll('.sidebar-button');
    ribbon.forEach(r => {
        r.addEventListener('click', () => {
            const target = r.getAttribute('data-page');
            if (
                r.getAttribute('data-disabled') === 'true' ||
                target === pageN ||
                target === activePageNavigation ||
                target === queuedPageNavigation?.target
            ) {
                return;
            }
            page(target).catch(error => {
                console.error('Unable to navigate from the sidebar:', error);
            });
        });
    });
    
    // Initialize Theme prior to initial page loads
    await themeRefresh(false); 
    bootProgress(0.28, 'Applying active theme');
    await setupLanguageWheel();
    bootProgress(0.38, 'Preparing language services');

    // Setup Controller Mode visual adjustments
    if (cmode) {
        document.body.style.zoom = '120%';
        document.querySelector('.glyph').style.display = 'flex';
        document.querySelector('.minimize-button').style.display = 'none';
        document.querySelector('.maximize-button').style.display = 'none';

        makeGlyphs([
            { icon: 'game_stick_left', description: "Move cursor" },
            { icon: 'game_stick_right', description: "Scroll" },
            { icon: 'cancel', description: "Click" },
            { icon: 'square_circle', description: "Right click" },
        ]);

        if (!localStorage.getItem('seenCModeAlert')) {
            localStorage.setItem('seenCModeAlert', 'true');
            htmlAlert(
                "Controller mode enabled", 
                "Controller mode is now enabled! Use Deltamod with your controller. Your left stick can help you move your mouse.", 
                [{ text: "Ok" }], 
                'stadia_controller'
            );
        }
    } else {
        document.querySelector('.glyph').style.display = 'none';
        if ((await window.deltamodBackend.invoke('getOS', [])).platform != 'linux') {
            window.addEventListener("gamepadconnected", async (event) => {
                if (await window.deltamodBackend.invoke('getUniqueFlag', ["CONTROLLER"]) === false) {
                    return;
                }
                if (!event.gamepad.id.toLowerCase().includes('dualshock') && !event.gamepad.id.toLowerCase().includes('dualsense')) {
                    return;
                }
                var res = await htmlAlert(
                    "Controller mode",
                    "It looks like you have a controller connected. Do you want to enable controller mode? Controller mode allows you to use Deltamod with your controller. Your left stick can help you move your mouse.",
                    [
                        { text: "Yes", resolveWith: true },
                        { text: "No", resolveWith: false }
                    ]
                );

                if (res) {
                    await window.deltamodBackend.invoke('cmode-on', []);
                }
            });
        }
    }

    if (await offerOfficialProfileImport()) {
        bootProgress(0.7, 'Waiting for profile import');
        finishBoot();
        return;
    }

    var loaded = await window.deltamodBackend.invoke('loadedDeltarune',[]);
    bootProgress(0.56, 'Finding installed games');

    if (await window.deltamodBackend.invoke('fetchSharedVariable',["gb1click"]) === true) {
        await page('goc-dl');
        finishBoot();
        return;
    }

    await new Promise(resolve => {
        var int = setInterval(async () => {
            if (renderedUser) {
                clearInterval(int);
                resolve();
            }
        }, 50);
    });
    bootProgress(0.72, 'Reading mod sources');

    // Main App Branching Route
    if (loaded.loaded) {
        var available = await window.deltamodBackend.invoke('fireUpdate', []);
        console.log('Update check complete. Update available:', available);
        bootProgress(0.84, 'Checking patch tools');

        var im = await invokeOptional('shouldGoIM', [], false);
        bootProgress(0.9, 'Preparing file overlay');
        if (im) {
            await page('installmanager');
        } else {
            await page('main');
        }
        finishBoot();
        (window.requestIdleCallback || (callback => setTimeout(callback, 0)))(warmPageMarkupCache);

        invokeOptional('executeArgumentCmd', [], null);
    } else {
        await page('locate');
        finishBoot();
        (window.requestIdleCallback || (callback => setTimeout(callback, 0)))(warmPageMarkupCache);
        document.querySelectorAll('.sidebar-button').forEach(button => button.setAttribute('data-disabled', 'true'));
        invokeOptional('executeArgumentCmd', [], null);
    }
})().catch(error => {
    console.error('Deltamod initialization failed:', error);
    window.DeltamodBoot?.fail('Continuing');
});

function closeAudio() {
    if (audio) {
        audio.pause();
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo) {
        themeVideo.pause();
    }
}

function openAudio() {
    if (audio && audio.src) {
        audio.play().catch(error => {
            // Silently fail if audio play is blocked
        });
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo?.src) {
        themeVideo.play().catch(() => {});
    }
}

/**
 * ==========================================
 * Late Execution Modules (Shop Checker)
 * ==========================================
 */
(async () => {
    renderuser();

    if ((await window.deltamodBackend.invoke('validateGamebananaToken'))) {
        document.getElementById('collectionsRibbon').style.display = 'inline-flex';
    }
})();
