/**
 * ==========================================
 * Deltamod Core Script
 * ==========================================
 */


// Global Variables & State
var audio = new Audio();
audio.preload = "none";
var currentAudio = "";
var currentAudioSource = "";
const menuAudioPositions = new Map();
var themeVideoSuspendTimer = null;
var suspendedThemeVideo = null;
var themeVideoLoadTimer = null;
var themeVideoRevealTimer = null;
var themeVideoFallbackActive = false;
var themeTransitionCleanupTimer = null;
var themeTransitionImpactTimer = null;
var themeTransitionFrameTimer = null;
var themeTransitionReleaseTimer = null;
var themeTransitionLastAudioTime = null;
var themeTransitionSfxTimers = [];
var themeTransitionActiveSfx = [];
var themeTransitionCompleted = false;
var themeSpriteAnimationTimers = [];
var menuAudioWasPlayingBeforeWindowInactive = false;
var theme = null;
var pageN = null;
var addedStyle = null;
var currentPageScript = null;
var update = false;
const MUSIC_VOLUME_STORAGE_KEY = 'deltamodMusicVolume';
const DEFAULT_MUSIC_VOLUME = 0.5;

function normalizeMusicVolume(value) {
    const numericValue = Number(value);
    return Number.isFinite(numericValue)
        ? Math.min(1, Math.max(0, numericValue))
        : DEFAULT_MUSIC_VOLUME;
}

function loadMusicVolume() {
    try {
        const storedValue = localStorage.getItem(MUSIC_VOLUME_STORAGE_KEY);
        return storedValue === null
            ? DEFAULT_MUSIC_VOLUME
            : normalizeMusicVolume(storedValue);
    } catch {
        return DEFAULT_MUSIC_VOLUME;
    }
}

var TARGET_MUSIC_VOLUME = loadMusicVolume();
var cmode = false; // Controller Mode
const MOTION = Object.freeze({
    fast: 140,
    standard: 180,
    easeOut: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1)'
});

function themeAssetUrl(themeConfig, folder, fileName) {
    if (themeConfig?.builtIn) {
        return window.deltamodBackend.assetUrl('app', `web/themes/${folder}/${fileName}`);
    }
    if (themeConfig?.runtimeLayout) {
        return window.deltamodBackend.assetUrl('theme', `${themeConfig.id}/${fileName}`);
    }
    return window.deltamodBackend.assetUrl('theme', `${folder}/${fileName}`);
}

function applyThemeStyles(themeConfig = theme) {
    const parsedThemeColor = window.ThemeSprites?.parseThemeColor(themeConfig.color)
        || [205, 68, 81];
    const [red, green, blue] = parsedThemeColor;
    const controlPalette = window.ThemeSprites?.controlPalette(parsedThemeColor) || {
        hoverColor: [213, 98, 109],
        inkColor: '#ffffff',
        hoverInkColor: '#000000'
    };
    const [hoverRed, hoverGreen, hoverBlue] = controlPalette.hoverColor;
    document.getElementById('dynamic-theme-styles').textContent = `
    /* Generated by Deltamod */
    :root {
        --theme-color: ${themeConfig.color};
        --theme-soul-color: ${themeConfig.soulColor || themeConfig.color};
        --theme-color-rgbaless: rgba(${red}, ${green}, ${blue}, 0.8);
        --theme-color-point2: rgba(${red}, ${green}, ${blue}, 0.2);
        --theme-color-point3: rgba(${red}, ${green}, ${blue}, 0.3);
        --theme-color-hover: rgb(${hoverRed}, ${hoverGreen}, ${hoverBlue});
        --theme-color-ink: ${controlPalette.inkColor};
        --theme-color-hover-ink: ${controlPalette.hoverInkColor};
    }
    input, select {
        box-shadow: inset 0 0 0 1px rgba(${red}, ${green}, ${blue}, 0.42);
    }
    input, progress {
        accent-color: ${themeConfig.color};
    }
    .sidebar {
        border-color: ${themeConfig.color};
    }
    ${themeConfig.specialCSS || ''}
    `;
}

function prefersReducedMotion() {
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

function releaseAudioBuffer() {
    rememberMenuAudioPosition();
    audio.pause();
    audio.currentTime = 0;
    audio.removeAttribute('src');
    audio.load();
    currentAudio = "";
    currentAudioSource = "";
}

function setMenuMusicVolume(value, { persist = true } = {}) {
    TARGET_MUSIC_VOLUME = normalizeMusicVolume(value);
    audio.volume = TARGET_MUSIC_VOLUME;

    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo) {
        themeVideo.volume = TARGET_MUSIC_VOLUME;
    }

    if (persist) {
        try {
            localStorage.setItem(MUSIC_VOLUME_STORAGE_KEY, String(TARGET_MUSIC_VOLUME));
        } catch (error) {
            console.warn('Unable to save the music volume:', error);
        }
    }
    return TARGET_MUSIC_VOLUME;
}

window.DeltamodAudioSettings = Object.freeze({
    getVolume: () => TARGET_MUSIC_VOLUME,
    setVolume: value => setMenuMusicVolume(value)
});

function rememberMenuAudioPosition() {
    if (currentAudioSource && Number.isFinite(audio.currentTime)) {
        menuAudioPositions.set(currentAudioSource, audio.currentTime);
    }
}

function configureMenuAudioPlayback(source) {
    const themeSource = theme?.mainSong
        ? themeAssetUrl(theme, 'mus', theme.mainSong)
        : '';
    const isThemeTrack = source === themeSource;
    const configuredRate = isThemeTrack ? Number(theme?.musicPlaybackRate) : 1;
    const playbackRate = Number.isFinite(configuredRate)
        ? Math.min(2, Math.max(0.5, configuredRate))
        : 1;

    audio.defaultPlaybackRate = playbackRate;
    audio.playbackRate = playbackRate;
    if ('preservesPitch' in audio) {
        audio.preservesPitch = isThemeTrack
            ? theme?.musicPreservesPitch !== false
            : true;
    }
}

function switchMenuAudioSource(source) {
    rememberMenuAudioPosition();
    audio.pause();

    const resumeAt = menuAudioPositions.get(source) || 0;
    currentAudioSource = source;

    const restorePosition = () => {
        if (currentAudioSource !== source) return;

        const latestResumeAt = menuAudioPositions.get(source) || resumeAt;
        const maximumPosition = Number.isFinite(audio.duration)
            ? Math.max(0, audio.duration - 0.44)
            : latestResumeAt;
        audio.currentTime = Math.min(latestResumeAt, maximumPosition);
    };

    // Register before loading. WebView2 can briefly retain the previous track's
    // readyState after assigning src; restoring then is discarded when the new
    // media pipeline resets currentTime to zero.
    audio.addEventListener('loadedmetadata', restorePosition, { once: true });
    audio.src = source;
    configureMenuAudioPlayback(source);
    audio.load();
}

function loopMenuAudio() {
    const loopBuffer = 0.44;
    if (Number.isFinite(audio.duration) && audio.currentTime > audio.duration - loopBuffer) {
        audio.currentTime = 0;
        audio.play().catch(() => {});
    }
}

audio.addEventListener('timeupdate', loopMenuAudio);
audio.addEventListener('timeupdate', synchronizeThemeTransition);

function themeUsesIntegratedVideoAudio(themeConfig = theme) {
    return Boolean(
        themeConfig?.backgroundVideo
        && themeConfig?.videoHasAudio
        && !themeVideoFallbackActive
    );
}

function getThemeBackgroundVideo() {
    return document.getElementById('theme-background-video');
}

function themeVideoUrl(themeConfig = theme) {
    if (!themeConfig?.backgroundVideo) return '';
    return themeAssetUrl(themeConfig, 'video', themeConfig.backgroundVideo);
}

function themeVideoRevealDelayMs(themeConfig = theme) {
    const configuredDelay = Number(themeConfig?.backgroundVideoRevealDelay);
    return Number.isFinite(configuredDelay)
        ? Math.min(30, Math.max(0, configuredDelay)) * 1000
        : 0;
}

const ROARING_KNIGHT_TRANSITION = Object.freeze({
    id: 'roaring-knight-monochrome-awakening',
    root: 'the-knight-transition',
    slashFrames: Object.freeze(Array.from(
        { length: 6 },
        (_, index) => `spr_roaringknight_front_slash_${index}.png`
    )),
    // The source canvases are identical, but the visible Knight is not centered
    // consistently inside them. These offsets keep the opaque subject aligned.
    frameOffsets: Object.freeze([
        Object.freeze({ x: 4.89, y: -5.32 }),
        Object.freeze({ x: 10.90, y: 3.90 }),
        Object.freeze({ x: 10.53, y: 3.19 }),
        Object.freeze({ x: 0, y: 0 }),
        Object.freeze({ x: -7.89, y: -10.64 }),
        Object.freeze({ x: -7.52, y: -10.28 })
    ])
});

const ROARING_KNIGHT_AWAKENED_FLAG = 'ROARING_KNIGHT_AWAKENED';

const ROARING_KNIGHT_SFX = Object.freeze({
    move: 'web/themes/sfx/the-knight-transition/knight-move.wav',
    impact: 'web/themes/sfx/the-knight-transition/knight-impact.wav',
    slash: 'web/assets/chara-easter-egg/slash.wav',
    damage: 'web/assets/chara-easter-egg/damage.wav'
});

const ROARING_KNIGHT_MONOCHROME_SPRITES = Object.freeze({
    'sbar/allmods.png': 'allmods.png',
    'sbar/collections.png': 'collections.png',
    'sbar/credits.png': 'credits.png',
    'sbar/installmanager.png': 'installmanager.png',
    'sbar/main.png': 'main.png',
    'sbar/options.png': 'options.png',
    'sbar/shop.png': 'shop.png',
    'img/packIcon.png': 'packIcon.png'
});

function clearThemeTransition() {
    clearTimeout(themeTransitionCleanupTimer);
    clearTimeout(themeTransitionImpactTimer);
    clearTimeout(themeTransitionFrameTimer);
    clearTimeout(themeTransitionReleaseTimer);
    themeTransitionCleanupTimer = null;
    themeTransitionImpactTimer = null;
    themeTransitionFrameTimer = null;
    themeTransitionReleaseTimer = null;
    themeTransitionSfxTimers.forEach(timer => clearTimeout(timer));
    themeTransitionSfxTimers = [];
    themeTransitionActiveSfx.forEach(sound => {
        sound.pause();
        sound.removeAttribute('src');
        sound.load();
    });
    themeTransitionActiveSfx = [];
    document.documentElement.classList.remove('roaring-knight-blackout');
    document.getElementById('theme-transition-overlay')?.remove();
}

function themeTransitionAssetUrl(fileName, themeConfig = theme) {
    return themeAssetUrl(
        themeConfig,
        'img',
        `${ROARING_KNIGHT_TRANSITION.root}/${fileName}`
    );
}

function setRoaringKnightSlashFrame(image, frameIndex) {
    const safeFrameIndex = Math.max(
        0,
        Math.min(ROARING_KNIGHT_TRANSITION.slashFrames.length - 1, frameIndex)
    );
    const offset = ROARING_KNIGHT_TRANSITION.frameOffsets[safeFrameIndex];
    image.src = themeTransitionAssetUrl(
        ROARING_KNIGHT_TRANSITION.slashFrames[safeFrameIndex]
    );
    image.style.setProperty('--frame-offset-x', `${offset.x}%`);
    image.style.setProperty('--frame-offset-y', `${offset.y}%`);
}

function roaringKnightSfxUrl(fileName) {
    return window.deltamodBackend.assetUrl('app', fileName);
}

function playRoaringKnightSfx(fileName, volume, playbackRate, stopAfterMs = 0) {
    const sound = new Audio(roaringKnightSfxUrl(fileName));
    sound.preload = 'auto';
    sound.volume = Math.min(1, Math.max(0, volume));
    sound.playbackRate = Math.min(4, Math.max(0.25, playbackRate));
    themeTransitionActiveSfx.push(sound);

    const releaseSound = () => {
        themeTransitionActiveSfx = themeTransitionActiveSfx.filter(item => item !== sound);
    };
    sound.addEventListener('ended', releaseSound, { once: true });
    sound.play().catch(error => {
        releaseSound();
        console.warn('Unable to play a Roaring Knight sound:', error);
    });

    if (stopAfterMs > 0) {
        const stopTimer = setTimeout(() => {
            sound.pause();
            releaseSound();
        }, stopAfterMs);
        themeTransitionSfxTimers.push(stopTimer);
    }
}

function scheduleRoaringKnightSfx(fileName, delay, volume, playbackRate, stopAfterMs = 0) {
    const timer = setTimeout(() => {
        playRoaringKnightSfx(fileName, volume, playbackRate, stopAfterMs);
    }, delay);
    themeTransitionSfxTimers.push(timer);
}

async function playRoaringKnightSoundSequence() {
    // An IPC failure must not silently mute a visual effect. An explicit disabled
    // SFX preference still wins.
    const sfxEnabled = await window.deltamodBackend
        .invoke('getUniqueFlag', ['SFX'])
        .catch(() => true);
    if (sfxEnabled === false || document.hidden) return;

    // DELTARUNE layers movement and multiple differently pitched cuts for the
    // Knight. Keep the same structure while using locally bundled assets.
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.move, 70, 0.48, 0.86);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.move, 390, 0.26, 1.18);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.move, 625, 0.34, 0.72);

    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.slash, 748, 0.58, 0.72);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.slash, 765, 0.46, 0.94);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.slash, 790, 0.32, 1.22);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.impact, 785, 0.34, 1.12, 950);
    scheduleRoaringKnightSfx(ROARING_KNIGHT_SFX.damage, 805, 0.42, 0.78);
}

function activeThemeVisualConfig() {
    if (
        theme?.transitionEffect === ROARING_KNIGHT_TRANSITION.id
        && (
            themeTransitionCompleted
            || document.documentElement.classList.contains('roaring-knight-awakened')
        )
    ) {
        return {
            ...theme,
            color: theme.transitionColor || 'rgb(198, 203, 209)',
            soulColor: theme.transitionSoulColor || '#FFFFFF'
        };
    }
    return theme;
}

function normalizeThemeSpriteSource(source) {
    return String(source || '').replace(/\\/g, '/').replace(/^\.\//, '');
}

function setRoaringKnightSpriteSet(awakened) {
    const selector = '[data-theme-sprite-source], [data-knight-original-sprite-source]';
    document.querySelectorAll(selector).forEach(image => {
        if (!(image instanceof HTMLImageElement)) return;

        if (awakened) {
            const originalSource = image.dataset.knightOriginalSpriteSource
                || image.dataset.themeSpriteSource;
            const spriteName = ROARING_KNIGHT_MONOCHROME_SPRITES[
                normalizeThemeSpriteSource(originalSource)
            ];
            if (!spriteName) return;

            if (!image.dataset.knightOriginalSpriteSource) {
                image.dataset.knightOriginalSpriteSource = originalSource;
                image.dataset.knightOriginalSpriteMode = image.dataset.themeSprite || 'accent';
            }
            delete image.dataset.themeSpriteSource;
            delete image.dataset.themeSprite;
            image.src = themeAssetUrl(
                theme,
                'img',
                `the-knight-monochrome/${spriteName}`
            );
            return;
        }

        const originalSource = image.dataset.knightOriginalSpriteSource;
        if (!originalSource) return;
        image.dataset.themeSpriteSource = originalSource;
        image.dataset.themeSprite = image.dataset.knightOriginalSpriteMode || 'accent';
        delete image.dataset.knightOriginalSpriteSource;
        delete image.dataset.knightOriginalSpriteMode;
        image.src = originalSource;
    });
}

function applyRoaringKnightPalette(awakened) {
    if (!theme) return;
    document.documentElement.classList.toggle('roaring-knight-awakened', awakened);
    const visualTheme = activeThemeVisualConfig();
    applyThemeStyles(visualTheme);
    setRoaringKnightSpriteSet(awakened);
    if (!awakened) {
        window.ThemeSprites?.apply(
            visualTheme.soulColor || visualTheme.color,
            document
        ).catch(error => {
            console.warn('Unable to restore themed sprites:', error);
        });
    }
    window.ThemeSprites?.applyAppIcon(visualTheme, window.deltamodBackend).catch(error => {
        console.warn('Unable to update the Roaring Knight application icon:', error);
    });
}

async function prepareThemeTransition(themeConfig = theme) {
    clearThemeTransition();
    setRoaringKnightSpriteSet(false);
    document.documentElement.classList.remove('roaring-knight-awakened');
    themeTransitionLastAudioTime = null;
    themeTransitionCompleted = false;
    if (themeConfig?.transitionEffect !== ROARING_KNIGHT_TRANSITION.id) return false;

    themeTransitionCompleted = await window.deltamodBackend
        .invoke('getUniqueFlag', [ROARING_KNIGHT_AWAKENED_FLAG])
        .catch(() => false) === true;

    ROARING_KNIGHT_TRANSITION.slashFrames.forEach(fileName => {
        const image = new Image();
        image.src = themeTransitionAssetUrl(fileName, themeConfig);
    });
    return themeTransitionCompleted;
}

function completeRoaringKnightAwakening() {
    themeTransitionCompleted = true;
    applyRoaringKnightPalette(true);
    window.deltamodBackend
        .invoke('setUniqueFlag', [ROARING_KNIGHT_AWAKENED_FLAG, true])
        .catch(error => {
            console.warn('Unable to persist the Roaring Knight awakening:', error);
        });
}

function playRoaringKnightTransition() {
    if (theme?.transitionEffect !== ROARING_KNIGHT_TRANSITION.id) return;
    if (themeTransitionCompleted) return;
    if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) {
        completeRoaringKnightAwakening();
        return;
    }

    clearThemeTransition();

    const overlay = document.createElement('div');
    overlay.id = 'theme-transition-overlay';
    overlay.className = 'theme-transition-overlay';
    overlay.setAttribute('aria-hidden', 'true');

    const blackout = document.createElement('span');
    blackout.className = 'theme-transition-blackout';

    const sigil = document.createElement('span');
    sigil.className = 'theme-transition-sigil';

    const knightStage = document.createElement('div');
    knightStage.className = 'theme-transition-knight-stage';
    for (let echoIndex = 3; echoIndex >= 0; echoIndex -= 1) {
        const knight = document.createElement('img');
        knight.className = `theme-transition-knight ${echoIndex === 0 ? 'is-main' : 'is-echo'}`;
        knight.alt = '';
        knight.style.setProperty('--echo-index', String(echoIndex));
        knight.style.setProperty('--echo-delay', `${echoIndex * 55}ms`);
        knight.style.setProperty('--echo-shift', `${echoIndex * -12}px`);
        knight.style.setProperty('--echo-scale', String(0.88 + echoIndex * 0.035));
        knight.style.setProperty('--echo-opacity', String(
            echoIndex === 0 ? 1 : Math.max(0.16, 0.56 - echoIndex * 0.12)
        ));
        setRoaringKnightSlashFrame(knight, 0);
        knightStage.appendChild(knight);
    }

    const soul = document.createElement('span');
    soul.className = 'theme-transition-soul';
    soul.textContent = '♥';

    const rift = document.createElement('span');
    rift.className = 'theme-transition-rift';

    const particles = document.createElement('div');
    particles.className = 'theme-transition-particles';
    for (let particleIndex = 0; particleIndex < 12; particleIndex += 1) {
        const particle = document.createElement('span');
        particle.style.setProperty('--particle-angle', `${particleIndex * 30}deg`);
        particle.style.setProperty('--particle-distance', `${20 + (particleIndex % 4) * 5}vmin`);
        particle.style.setProperty('--particle-delay', `${particleIndex * 18}ms`);
        particles.appendChild(particle);
    }

    overlay.append(blackout, sigil, particles, knightStage, soul, rift);
    document.body.appendChild(overlay);
    document.documentElement.classList.add('roaring-knight-blackout');
    requestAnimationFrame(() => overlay.classList.add('is-active'));
    void playRoaringKnightSoundSequence();

    themeTransitionImpactTimer = setTimeout(() => {
        if (!overlay.isConnected) return;
        overlay.classList.add('is-impacting');
        let frameIndex = 0;
        const advanceSlashFrame = () => {
            if (!overlay.isConnected) return;
            knightStage.querySelectorAll('.theme-transition-knight').forEach(knight => {
                setRoaringKnightSlashFrame(knight, frameIndex);
            });
            frameIndex += 1;
            if (frameIndex < ROARING_KNIGHT_TRANSITION.slashFrames.length) {
                themeTransitionFrameTimer = setTimeout(advanceSlashFrame, 64);
            }
        };
        advanceSlashFrame();
    }, 760);

    themeTransitionReleaseTimer = setTimeout(() => {
        if (!overlay.isConnected) return;
        overlay.classList.add('is-releasing');
        document.documentElement.classList.remove('roaring-knight-blackout');
        completeRoaringKnightAwakening();
    }, 1575);

    themeTransitionCleanupTimer = setTimeout(clearThemeTransition, 2100);
}

function synchronizeThemeTransition() {
    const cueTime = Number(theme?.transitionCueTime);
    const expectedAudioSource = theme?.mainSong
        ? themeAssetUrl(theme, 'mus', theme.mainSong)
        : '';
    if (
        themeTransitionCompleted
        || theme?.transitionEffect !== ROARING_KNIGHT_TRANSITION.id
        || !Number.isFinite(cueTime)
        || currentAudioSource !== expectedAudioSource
    ) {
        themeTransitionLastAudioTime = null;
        return;
    }

    const currentTime = audio.currentTime;
    if (!Number.isFinite(currentTime)) return;
    if (themeTransitionLastAudioTime === null) {
        themeTransitionLastAudioTime = currentTime;
        return;
    }
    if (currentTime < themeTransitionLastAudioTime) {
        clearThemeTransition();
        applyRoaringKnightPalette(false);
        themeTransitionLastAudioTime = currentTime;
        return;
    }
    if (
        themeTransitionLastAudioTime < cueTime
        && currentTime >= cueTime
        && !document.hidden
        && document.hasFocus()
    ) {
        playRoaringKnightTransition();
    }
    themeTransitionLastAudioTime = currentTime;
}

function setThemeVideoAudioEnabled(enabled) {
    const video = getThemeBackgroundVideo();
    if (!video || !themeUsesIntegratedVideoAudio()) return;
    video.muted = !enabled;
    video.volume = enabled ? TARGET_MUSIC_VOLUME : 0;
    if (video.src && video.paused) {
        video.play().catch(() => {});
    }
}

function suspendThemeBackgroundVideo() {
    const video = getThemeBackgroundVideo();
    if (!video?.src || !theme?.backgroundVideo) return;

    suspendedThemeVideo = {
        source: video.dataset.source,
        currentTime: Number.isFinite(video.currentTime) ? video.currentTime : 0
    };
    video.pause();
    video.volume = 0;
}

function resumeThemeBackgroundVideo(audioEnabled) {
    const video = getThemeBackgroundVideo();
    const expectedSource = themeVideoUrl();
    if (!video || !suspendedThemeVideo || suspendedThemeVideo.source !== expectedSource) {
        return false;
    }

    const resumeAt = suspendedThemeVideo.currentTime;
    suspendedThemeVideo = null;
    video.muted = !audioEnabled;
    video.volume = audioEnabled ? TARGET_MUSIC_VOLUME : 0;

    const resumePlayback = () => {
        const maximumPosition = Number.isFinite(video.duration)
            ? Math.max(0, video.duration - 0.44)
            : resumeAt;
        const targetTime = Math.min(resumeAt, maximumPosition);
        if (Math.abs(video.currentTime - targetTime) > 0.05) {
            video.currentTime = targetTime;
        }
        video.play().catch(() => {});
    };

    if (video.readyState >= HTMLMediaElement.HAVE_METADATA) {
        resumePlayback();
    } else {
        video.addEventListener('loadedmetadata', resumePlayback, { once: true });
    }
    return true;
}

function scheduleThemeVideoSuspension() {
    clearTimeout(themeVideoSuspendTimer);
    const video = getThemeBackgroundVideo();
    if (video?.src) {
        suspendThemeBackgroundVideo();
    }
}

function clearThemeSpriteAnimations() {
    themeSpriteAnimationTimers.forEach(timer => clearInterval(timer));
    themeSpriteAnimationTimers = [];
    const layer = document.getElementById('theme-sprite-layer');
    if (!layer) return;
    layer.replaceChildren();
    layer.hidden = true;
}

function applyThemeSpriteAnimations() {
    clearThemeSpriteAnimations();
    const layer = document.getElementById('theme-sprite-layer');
    const sprites = Array.isArray(theme?.animatedEnvironment) ? theme.animatedEnvironment : [];
    if (!layer || sprites.length === 0 || theme?.backgroundVideo) return;

    const stage = document.createElement('div');
    stage.className = 'theme-sprite-stage';
    const [ratioWidth, ratioHeight] = String(theme.environmentStageRatio || '16 / 9')
        .split('/')
        .map(value => Number(value.trim()));
    const stageRatio = Number.isFinite(ratioWidth) && Number.isFinite(ratioHeight) && ratioHeight > 0
        ? ratioWidth / ratioHeight
        : 16 / 9;
    stage.style.setProperty('--environment-cover-width', `${stageRatio * 100}vh`);
    stage.style.setProperty('--environment-cover-height', `${100 / stageRatio}vw`);
    layer.appendChild(stage);

    sprites.forEach((sprite, spriteIndex) => {
        const frames = Array.isArray(sprite.frames)
            ? sprite.frames.filter(frame => typeof frame === 'string' && frame.length > 0)
            : [];
        if (frames.length === 0) return;

        const image = document.createElement('img');
        image.className = `theme-environment-sprite anchor-${sprite.anchor || 'center'} motion-${sprite.motion || 'pulse'}`;
        image.alt = '';
        image.decoding = 'async';
        image.draggable = false;
        image.style.left = `${Number(sprite.left) || 50}%`;
        image.style.top = `${Number(sprite.top) || 50}%`;
        image.style.width = `${Math.max(0.25, Number(sprite.width) || 3)}%`;
        image.style.opacity = `${Math.min(1, Math.max(0, Number(sprite.opacity) || 1))}`;
        if (typeof sprite.filter === 'string' && sprite.filter.trim()) {
            image.style.filter = sprite.filter;
        }
        image.style.setProperty(
            '--sprite-delay',
            `${Number.isFinite(Number(sprite.delay)) ? Number(sprite.delay) : spriteIndex * -180}ms`
        );

        const frameUrls = frames.map(frame => themeAssetUrl(theme, 'img', frame));
        frameUrls.forEach(source => {
            const preload = new Image();
            preload.src = source;
        });
        image.src = frameUrls[0];
        stage.appendChild(image);

        if (frameUrls.length > 1 && !prefersReducedMotion()) {
            const frameDuration = Math.max(70, Math.round(1000 / Math.max(1, Number(sprite.fps) || 5)));
            let frameIndex = Math.abs(Number(sprite.frameOffset) || 0) % frameUrls.length;
            image.src = frameUrls[frameIndex];
            const timer = setInterval(() => {
                if (document.hidden || document.documentElement.classList.contains('window-inactive') || prefersReducedMotion()) return;
                frameIndex = (frameIndex + 1) % frameUrls.length;
                image.src = frameUrls[frameIndex];
            }, frameDuration);
            themeSpriteAnimationTimers.push(timer);
        }
    });

    layer.hidden = stage.childElementCount === 0;
}

function applyThemeBackground() {
    const background = document.querySelector('.bg');
    const video = getThemeBackgroundVideo();
    if (!background || !video) return;

    const backgroundImage = `url("${themeAssetUrl(theme, 'img', theme.background)}")`;
    delete background.dataset.themeMotion;
    background.style.removeProperty('--theme-motion-duration');
    background.style.backgroundSize = theme.backgroundSize || 'cover';
    background.style.backgroundPosition = theme.backgroundPosition || 'center';
    background.style.backgroundColor = theme.backgroundColor || '#050505';
    applyThemeSpriteAnimations();
    const showVideoPoster = theme.backgroundVideoPoster !== false;
    background.style.backgroundImage = !theme.backgroundVideo || showVideoPoster
        ? backgroundImage
        : 'none';
    if (!theme.backgroundVideo) {
        clearTimeout(themeVideoSuspendTimer);
        clearTimeout(themeVideoLoadTimer);
        clearTimeout(themeVideoRevealTimer);
        suspendedThemeVideo = null;
        themeVideoFallbackActive = false;
        video.pause();
        video.hidden = true;
        video.classList.remove('is-revealed');
        background.classList.remove('is-covered-by-video');
        video.removeAttribute('src');
        video.removeAttribute('poster');
        video.removeAttribute('data-source');
        video.load();
        return;
    }

    const source = themeVideoUrl();
    const sourceChanged = video.dataset.source !== source;
    clearTimeout(themeVideoLoadTimer);
    clearTimeout(themeVideoRevealTimer);
    themeVideoFallbackActive = false;
    if (showVideoPoster) {
        video.poster = themeAssetUrl(theme, 'img', theme.background);
    } else {
        video.removeAttribute('poster');
    }
    if (sourceChanged) {
        background.classList.remove('is-covered-by-video');
    }
    video.hidden = sourceChanged;
    video.loop = true;
    video.onplaying = () => {
        clearTimeout(themeVideoLoadTimer);
        video.hidden = false;
        if (video.classList.contains('is-revealed')) return;

        const revealVideo = () => {
            if (video.dataset.source !== source) return;
            video.removeAttribute('poster');
            background.classList.add('is-covered-by-video');
            video.classList.add('is-revealed');
            background.style.backgroundImage = 'none';
        };
        const revealDelay = themeVideoRevealDelayMs();
        if (revealDelay > 0) {
            themeVideoRevealTimer = setTimeout(revealVideo, revealDelay);
        } else {
            revealVideo();
        }
    };
    video.onerror = () => {
        void fallBackFromThemeVideo(video, background, `media error ${video.error?.code || 'unknown'}`);
    };
    if (sourceChanged) {
        suspendedThemeVideo = null;
        video.classList.remove('is-revealed');
        video.muted = true;
        video.volume = 0;
        video.dataset.source = source;
        video.src = source;
    } else if (video.classList.contains('is-revealed')) {
        video.hidden = false;
        video.removeAttribute('poster');
        background.classList.add('is-covered-by-video');
        background.style.backgroundImage = 'none';
    }
    video.play().catch(error => {
        void fallBackFromThemeVideo(video, background, error?.name || 'playback rejected');
    });
    const themeVideoReadyTimeout = window.DeltamodLinuxCompat?.isLinuxTauri
        && window.DeltamodLinuxCompat.getMode?.() === 'quality'
        ? 20000
        : 5000;
    themeVideoLoadTimer = setTimeout(() => {
        if (video.readyState < HTMLMediaElement.HAVE_FUTURE_DATA) {
            void fallBackFromThemeVideo(video, background, 'load timeout');
        }
    }, themeVideoReadyTimeout);
}

async function fallBackFromThemeVideo(video, background, reason) {
    if (themeVideoFallbackActive || video.dataset.source !== themeVideoUrl()) return;
    themeVideoFallbackActive = true;
    clearTimeout(themeVideoLoadTimer);
    clearTimeout(themeVideoRevealTimer);
    video.pause();
    video.hidden = true;
    video.classList.remove('is-revealed');
    background.classList.remove('is-covered-by-video');
    video.removeAttribute('src');
    video.removeAttribute('data-source');
    video.load();
    background.style.backgroundImage = `url("${themeAssetUrl(theme, 'img', theme.background)}")`;
    console.warn(`Theme video unavailable (${reason}); using poster and audio fallback.`);

    if (await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"])) {
        currentAudio = 'mainTheme.mp3';
        switchMenuAudioSource(themeAssetUrl(theme, 'mus', theme.mainSong));
        audio.loop = true;
        audio.volume = TARGET_MUSIC_VOLUME;
        await audio.play().catch(() => {});
    }
}

window._onClosePage = window._onClosePage || [];

const PAGE_STYLESHEET_OVERRIDES = Object.freeze({
    allmods: './views/main/main.css',
    'allmods-v2': './views/main/main.css'
});

const PAGE_REGISTRY = Object.freeze(Object.fromEntries([
    'allmods',
    'allmods-v2',
    'collection-exportchoose',
    'collections',
    'credits',
    'deleteall',
    'gamebanana-browse',
    'gamebanana-leave-comment',
    'goc-dl',
    'installmanager',
    'locate',
    'main',
    'options',
    'patching',
    'themesel'
].map(name => [name, Object.freeze({
    name,
    html: `./views/${name}/index.html`,
    script: `./views/${name}/index.js`,
    base: `./views/${name}/`,
    stylesheet: PAGE_STYLESHEET_OVERRIDES[name] || null
})])));

const pageMarkupCache = new Map();

function loadPageMarkup(pageDefinition) {
    if (!pageMarkupCache.has(pageDefinition.html)) {
        const request = fetch(pageDefinition.html)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`Failed to load page ${pageDefinition.name}: HTTP ${response.status}`);
                }
                return response.text();
            })
            .catch(error => {
                pageMarkupCache.delete(pageDefinition.html);
                throw error;
            });
        pageMarkupCache.set(pageDefinition.html, request);
    }
    return pageMarkupCache.get(pageDefinition.html);
}

function warmPageMarkupCache() {
    const likely = ['main', 'allmods', 'options', 'gamebanana-browse'];
    const next = () => {
        const name = likely.shift();
        if (!name) return;
        loadPageMarkup(PAGE_REGISTRY[name]).catch(() => {}).finally(() => {
            (window.requestIdleCallback || (callback => setTimeout(callback, 100)))(next);
        });
    };
    next();
}

function loadPageScript(pageDefinition) {
    if (currentPageScript) {
        currentPageScript.remove();
        currentPageScript = null;
    }

    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = pageDefinition.script;
        script.async = false;
        script.dataset.pageScript = pageDefinition.name;
        script.addEventListener('load', () => resolve(), { once: true });
        script.addEventListener(
            'error',
            () => reject(new Error(`Failed to load script for page: ${pageDefinition.name}`)),
            { once: true }
        );
        currentPageScript = script;
        document.body.appendChild(script);
    });
}

/**
 * Wrapper for invoking Electron IPC calls.
 */
async function invoke(...params) {
    return window.deltamodBackend.invoke(...params);
}

/**
 * Generates and appends glyph icons to the DOM.
 * @param {Array} jsonArr - Array of glyph objects { icon, description }
 */
async function makeGlyphs(jsonArr) {
    var glyphContainer = document.querySelector('.glyph');
    glyphContainer.innerHTML = '';
    
    jsonArr.forEach(glyph => {
        var glyphIconElement = document.createElement('span');
        glyphIconElement.classList.add('material-symbols-outlined');
        glyphIconElement.innerText = glyph.icon;

        var glyphDescElement = document.createElement('span');
        glyphDescElement.innerText = glyph.description;

        glyphContainer.appendChild(glyphIconElement);
        glyphContainer.appendChild(glyphDescElement);
    });
}

async function reapplyHAStyles() {
    var alignment = localStorage.getItem('alertAlignment') || 'Bottom';
    if (!localStorage.getItem('alertAlignment')) {
        localStorage.setItem('alertAlignment', alignment);
    }
    var haDynamicStyle = document.getElementById('haDynamicStyle');
    if (!haDynamicStyle) {
        haDynamicStyle = document.createElement('style');
        haDynamicStyle.id = 'haDynamicStyle';
        document.head.appendChild(haDynamicStyle);
    }
    haDynamicStyle.innerHTML = await fetch('./haAlignments/' + alignment + '.css').then(res => res.text());
}

/**
 * Prompts the user to leave Controller Mode.
 */
async function promptLeaveCMode() {
    htmlAlert(
        "Exit controller mode", 
        "Are you sure you want to exit controller mode? If you exit controller mode, Deltamod will close.", 
        [
            { text: "Yes", resolveWith: true },
            { text: "No", resolveWith: false }
        ], 
        'stadia_controller'
    ).then(async (result) => {
        if (result) {
            await window.deltamodBackend.invoke('cmode-off', []);
        }
    });
}

/**
 * Plays the "rew" SFX.
 */
async function rew() {
    if (await window.deltamodBackend.invoke('getUniqueFlag', ["SFX"]) === false) {
        return;
    }
    var a = new Audio();
    a.src = 'audio/rew.mp3';
    a.play();
}

/**
 * Brightens an RGB color by a specified amount.
 */
function brightenColor(r, g, b, amount) {
    r = Math.min(255, r + amount);
    g = Math.min(255, g + amount);
    b = Math.min(255, b + amount);
    return `rgb(${r}, ${g}, ${b})`;
}

// Window Management
function toggleFullscreen() { window.deltamodBackend.invoke('toggleFullscreen', []); }
function toggleMinimize() { window.deltamodBackend.invoke('minimizeMe', []); }
function closeCommunity() {
    window.deltamodBackend.invoke('quitCommunityForEasterEgg', []).catch(() => window.close());
}
function genbtnstyles() { /* deprecated */ }

// Play rewind SFX on specific preload trigger
window.preloadAPI.onWRA(() => rew());

function error() {
    fetch('http://google.com'); // Force an error trigger if used in a specific context
}

function disableElem(elem) {
    if (!elem) return;
    elem.style.pointerEvents = 'none';
    elem.style.opacity = '0';
}
function enableElem(elem) {
    if (!elem) return;
    elem.style.pointerEvents = 'auto';
    elem.style.opacity = '1';
}

/**
 * ==========================================
 * Custom HTML Alert System
 * ==========================================
 */
// The dialog queue owns focus, background inertness, and false/zero results.
function htmlAlert(title, message, buttons, specialIcon) {
    return window.DeltamodDialogs.show(title, message, buttons, specialIcon);
}

function htmlAlertRaw(title, message, buttons, specialIcon) {
    return htmlAlert(title, message, buttons, specialIcon);
}

function credits(funny) {
    page('credits');
}

/**
 * ==========================================
 * Preload API Listeners (Updates, Logging)
 * ==========================================
 */
window.preloadAPI.onUpdateAvailable((info) => {
    console.log('Update available:', info.version);
    update = true;
    window.ustack = {};
    window.ustack.updateInfo = info;

    htmlAlert(
        'Update available', 
        `A new version of Deltamod Community (${info.version}) is available for download. Do you wish to update?`,
        [
            { text: 'Yes', resolveWith: "a" },
            { text: 'No', rejectWith: "a" }
        ], 
        'update'
    ).then(async () => {
        await window.deltamodBackend.invokeOptional('start-update', [], false);
    }).catch(async () => {
        await window.deltamodBackend.invokeOptional('ignore-update', [], false);
    });
});

window.preloadAPI.onDLMODProgress((info) => window.currentPageStack.dlmod && window.currentPageStack.dlmod(info));
window.preloadAPI.onProtocolDownloadProgress((info) => window.currentPageStack.onDLP && window.currentPageStack.onDLP(info.percentage));
window.preloadAPI.onProfileImportProgress((info) => window.currentPageStack.profileImportProgress && window.currentPageStack.profileImportProgress(info));
window.preloadAPI.onHashProgress((info) => window.currentPageStack.hashProgress && window.currentPageStack.hashProgress(info));
window.preloadAPI.onRefresh(() => page(pageN));
window.preloadAPI.onFinishedPatch(() => window.currentPageStack.fp && window.currentPageStack.fp());
window.preloadAPI.onGPL((message) => window.currentPageStack.gpl && window.currentPageStack.gpl(message));
window.preloadAPI.onPage((title) => page(title));
window.preloadAPI.onAudio((stat) => stat ? openAudio() : closeAudio());
window.preloadAPI.onLeaveControllerMode(() => promptLeaveCMode());

function sanitizeHTML(str) {
    var temp = document.createElement('div');
    temp.textContent = str;
    return temp.innerHTML;
}

function formatBytes(bytes) {
    if (!Number.isFinite(bytes) || bytes < 0) return 'an unknown amount of space';
    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    let value = bytes;
    let unit = 0;
    while (value >= 1024 && unit < units.length - 1) {
        value /= 1024;
        unit += 1;
    }
    return `${value.toFixed(unit === 0 ? 0 : 1)} ${units[unit]}`;
}

async function offerOfficialProfileImport() {
    try {
        const summary = await window.communityAPI.profile.summary();
        if (!summary.exists || summary.previousImport || localStorage.getItem('communityMigrationPromptDismissed') === 'true') {
            return false;
        }

        const choice = await htmlAlert(
            'Import your Deltamod data',
            `Deltamod ${summary.version || ''} was found with ${summary.installations} installation(s), ${summary.mods} mod(s), and ${summary.themes} custom theme(s). A safe Community copy needs ${formatBytes(summary.totalBytes)}. Official Deltamod will not be changed.`,
            [
                { text: 'Review and import', resolveWith: 'import' },
                { text: 'Later', resolveWith: 'later' }
            ],
            'database'
        );

        if (choice === 'import') {
            window._pageArguments = { cat: 'data' };
            await page('options');
            return true;
        }

        localStorage.setItem('communityMigrationPromptDismissed', 'true');
    } catch (error) {
        console.warn('Could not inspect the official Deltamod profile:', error.message || error);
    }
    return false;
}

// Override console methods to tunnel logs through Electron IPC
console.log = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'LOG', pageN]); };
console.warn = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'WARN', pageN]); };
console.error = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'ERROR', pageN]); };
console.info = function(...args) { window.deltamodBackend.invoke('log', [args.join(' '), 'INFO', pageN]); };

function uppercaseFirst(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

function adaptForIcons(element) {
    element.style.display = 'flex';
    element.style.alignItems = 'left';
    element.style.gap = '5px';
    element.style.justifyContent = 'left';
    return element;
}

function icon(name, fontSize) {
    return window.DeltamodIcons.markup(name, fontSize);
}

async function invokeOptional(channel, data, fallback) {
    return window.deltamodBackend.invokeOptional(channel, data, fallback);
}

async function signalBenchmarkReadiness() {
    if (
        pageN !== 'main'
        || document.documentElement.classList.contains('deltamod-route-pending')
        || !window.deltamodBackend.isCommandAvailable('benchmark:rendererReady')
    ) return false;
    return window.deltamodBackend.invoke('benchmark:rendererReady', [{
        page: 'main',
        routeGuardCleared: true
    }]);
}

window.addEventListener('deltamod-route-ready', () => {
    signalBenchmarkReadiness().catch(() => {});
});

// The React boot overlay is optional so the vanilla renderer remains usable if
// a development build is missing the generated bundle. These helpers also keep
// loading milestones in one place instead of coupling page code to React.
function bootProgress(progress, status) {
    window.DeltamodBoot?.setProgress(progress, status);
}

function bootTheme(themeConfig) {
    if (!themeConfig) return;
    window.DeltamodBoot?.setTheme({
        themeColor: themeConfig.color,
        soulColor: themeConfig.soulColor || themeConfig.color,
        backgroundImage: themeConfig.background
            ? themeAssetUrl(themeConfig, 'img', themeConfig.background)
            : undefined,
        backgroundVideo: themeConfig.backgroundVideo ? themeVideoUrl(themeConfig) : undefined,
        readyAtVideoTime: Number.isFinite(themeConfig.bootSyncTime)
            ? themeConfig.bootSyncTime
            : undefined,
    });
}

function finishBoot() {
    window.DeltamodBoot?.finish();
}

/**
 * ==========================================
 * Theme & Audio Rendering
 * ==========================================
 */

/**
 * Refreshes the application theme and applies background/music.
 * @param {boolean} refreshAudio - Whether to also reload and play the main theme song.
 */
async function themeRefresh(refreshAudio = true) {
    const themeName = await window.deltamodBackend.invoke('getTheme', []);
    const themePath = `data/${themeName}.theme.json`;
    let response;
    let builtIn = false;
    let runtimeLayout = false;
    try {
        response = await fetch(window.deltamodBackend.assetUrl('theme', themePath));
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
    } catch (error) {
        try {
            response = await fetch(window.deltamodBackend.assetUrl('theme', `${themeName}/theme.json`));
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            runtimeLayout = true;
        } catch {
            response = await fetch(window.deltamodBackend.assetUrl('app', `web/themes/${themePath}`));
            if (!response.ok) throw error;
            builtIn = true;
        }
    }
    theme = await response.json();
    theme.builtIn = builtIn;
    theme.runtimeLayout = runtimeLayout;
    if (runtimeLayout) {
        theme.background = theme.background || theme.icon;
        theme.mainSong = theme.mainSong || theme.music;
        theme.description = theme.description || 'Custom theme';
        theme.musicTrack = theme.musicTrack || (theme.mainSong ? 'Custom audio' : 'No custom audio');
        theme.color = theme.color || 'rgb(205, 68, 81)';
        theme.soulColor = theme.soulColor || '#FF0000';
    }
    await prepareThemeTransition(theme);
    bootTheme(activeThemeVisualConfig());
    applyThemeBackground();
    applyThemeStyles(theme);
    if (themeTransitionCompleted) {
        applyRoaringKnightPalette(true);
    }
    // The seasonal layer stays hidden until these CSS variables contain the
    // active theme, preventing a default-color flash during startup or swaps.
    window.SeasonalEvents?.setThemeReady(true);
    const visualTheme = activeThemeVisualConfig();
    window.ThemeSprites?.apply(visualTheme.soulColor || visualTheme.color, document).catch(error => {
        console.warn('Unable to recolor theme sprites:', error);
    });
    window.ThemeSprites?.applyAppIcon(visualTheme, window.deltamodBackend).catch(error => {
        console.warn('Unable to update the themed application icon:', error);
    });
    
    if (refreshAudio) {
        const shouldPlayAudio = await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"]);
        if (themeUsesIntegratedVideoAudio()) {
            releaseAudioBuffer();
            setThemeVideoAudioEnabled(shouldPlayAudio);
        } else if (shouldPlayAudio && theme.mainSong) {
            audio.loop = true;
            audio.volume = TARGET_MUSIC_VOLUME;
            currentAudio = 'mainTheme.mp3';
            switchMenuAudioSource(themeAssetUrl(theme, 'mus', theme.mainSong));
            await audio.play().catch(() => {});
        } else {
            releaseAudioBuffer();
        }
    }
}

window.preloadAPI.onThemeChange(themeRefresh);
window.ThemeSprites?.observe(() => {
    const visualTheme = activeThemeVisualConfig();
    return visualTheme?.soulColor || visualTheme?.color;
});

let lockRandoms = false;

function elisten(element, event, handler) {
    element.addEventListener(event, handler);
    window._eventListeners = window._eventListeners || [];
    window._eventListeners.push({ element, event, handler });
}

/**
 * Navigates to a specific internal page and processes HTML/CSS injections.
 * @param {string} name - The identifier of the page to load.
 */
let activePageNavigation = null;
let queuedPageNavigation = null;
let pageNavigationDrain = null;

function page(name) {
    const forceReload = name === '';
    const target = forceReload ? pageN : name;

    if (!target) {
        return Promise.resolve(false);
    }

    if (!forceReload && (
        target === activePageNavigation ||
        target === queuedPageNavigation?.target
    )) {
        return Promise.resolve(false);
    }

    const navigation = new Promise((resolve, reject) => {
        if (queuedPageNavigation) {
            queuedPageNavigation.resolve(false);
        }
        queuedPageNavigation = { target, resolve, reject };
    });

    schedulePageNavigationDrain();

    return navigation;
}

function schedulePageNavigationDrain() {
    if (pageNavigationDrain) return;

    pageNavigationDrain = drainPageNavigations().finally(() => {
        pageNavigationDrain = null;
        if (queuedPageNavigation) {
            schedulePageNavigationDrain();
        }
    });
}

async function drainPageNavigations() {
    while (queuedPageNavigation) {
        const navigation = queuedPageNavigation;
        queuedPageNavigation = null;
        activePageNavigation = navigation.target;

        try {
            await renderPage(navigation.target);
            navigation.resolve(true);
        } catch (error) {
            window.DeltamodUI.showError(document.querySelector('.viewport'), error, () => page(navigation.target));
            navigation.reject(error);
        } finally {
            activePageNavigation = null;
        }
    }
}

async function renderPage(name) {
    if (name === '') name = pageN;
    if (!PAGE_REGISTRY[name]) throw new Error(`Blocked unknown page: ${String(name)}`);
    const previousFocus = document.activeElement;
    const focusContent = Boolean(previousFocus?.matches?.('.sidebar-button:focus-visible'));
    rew();

    // Clear existing intervals/listeners to prevent memory leaks
    try {
        window._intervals.forEach(clearInterval);
    } catch(e) {
        console.log('No intervals to clear');
    }
    window._intervals = [];

    window._eventListeners = window._eventListeners || [];
    window._eventListeners.forEach(({ element, event, handler }) => {
        element.removeEventListener(event, handler);
    });
    window._eventListeners = [];

    window._onClosePage = window._onClosePage || [];
    window._onClosePage.forEach(func => func());
    window._onClosePage = [];

    if (currentPageScript) {
        currentPageScript.remove();
        currentPageScript = null;
    }

    if (addedStyle) {
        addedStyle.remove();
        addedStyle = null;
    }
    
    if (name == "") {
        name = pageN;
    }

    // Prevents escaping to home if game is baked
    if (name === 'main' && PAGE_REGISTRY.bakedhome && await window.deltamodBackend.invoke('isBaked', [])) {
        name = 'bakedhome';
    }
    const pageDefinition = PAGE_REGISTRY[name];
    if (!pageDefinition) {
        throw new Error(`Blocked unknown page: ${String(name)}`);
    }

    // Keep navigation immediate. Animating the full viewport promotes every
    // blurred panel to a large compositor surface and retains substantial GPU
    // memory after each page change.
    const viewport = document.querySelector('.viewport');
    viewport.style.animation = 'none';
    window.deltamodBackend.invoke('showWindow', []);

    // Load theme if not yet initialized
    if (!theme) {
        await themeRefresh(false); 
    }

    window.currentPageStack = {};

    // Process Page HTML
    var purifiedHTML = await loadPageMarkup(pageDefinition);
    await window.Localization?.ready;
    purifiedHTML = window.Localization?.replaceTokens(purifiedHTML) || purifiedHTML;
    
    var runScripts = false;
    var changeAudio = false;

    // Detect and queue JS execution
    if (purifiedHTML.includes('JSL')) {
        purifiedHTML = purifiedHTML.replace('JSL', '');
        runScripts = true;
    }

    // Load internal stylesheet tags
    if (purifiedHTML.includes('STYLESHEET[')) {
        var stylesheetSrc = purifiedHTML.match(/STYLESHEET\[(.*?)\]/);
        if (stylesheetSrc && stylesheetSrc[1]) {
            if (addedStyle) addedStyle.remove();
            addedStyle = document.createElement('link');
            addedStyle.rel = 'stylesheet';
            addedStyle.dataset.pageStylesheet = name;
            if (pageDefinition.stylesheet) {
                addedStyle.href = pageDefinition.stylesheet;
            } else {
                if (!/^[a-z0-9_-]+$/i.test(stylesheetSrc[1])) {
                    throw new Error(`Blocked unsafe stylesheet name on page ${name}.`);
                }
                addedStyle.href = `${pageDefinition.base}${stylesheetSrc[1]}.css`;
            }
            document.getElementById('head').appendChild(addedStyle);
        }
        purifiedHTML = purifiedHTML.replace(/STYLESHEET\[(.*?)\]/g, '');
    } else if (addedStyle) {
        addedStyle.remove();
        addedStyle = null;
    }

    // Handle NO-SIDEBAR tag
    if (purifiedHTML.includes('NO-SIDEBAR')) {
        purifiedHTML = purifiedHTML.replace('NO-SIDEBAR', '');
        ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => { button.setAttribute('data-disabled', 'true'); button.setAttribute('aria-disabled', 'true'); if (button.tagName === 'BUTTON') button.disabled = true; });
    } else {
        ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => { button.setAttribute('data-disabled', 'false'); button.setAttribute('aria-disabled', 'false'); if (button.tagName === 'BUTTON') button.disabled = false; });
    }

    // Extract Title Tag
    var title = purifiedHTML.match(/TITLE\[(.*?)\]/);
    purifiedHTML = purifiedHTML.replace(/TITLE\[(.*?)\]/g, '');
    const pageTitle = window.Localization?.translateKnownText(
        title?.[1] || 'Deltamod Community'
    ) || title?.[1] || 'Deltamod Community';
    const pageTitleElement = document.getElementById('pageTitle');
    if (pageTitleElement) {
        pageTitleElement.textContent = pageTitle;
    }

    // Extract Exclude Audio Tag
    var themeAudioExclude = purifiedHTML.match(/THEME-AUDIO-EXCLUDE\[(.*?)\]/);
    purifiedHTML = purifiedHTML.replace(/THEME-AUDIO-EXCLUDE\[(.*?)\]/g, '');

    // Process Audio Tag
    if (true) {
        var audioSrc = purifiedHTML.match(/AUDIO\[(.*?)\]/);
        console.log('Audio source found:' + audioSrc);
        
        if (!audioSrc || !audioSrc[1]) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }
        if (theme.id == themeAudioExclude?.[1]) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }
        const [dynamicMusic, shouldPlayAudio] = await Promise.all([
            window.deltamodBackend.invoke('getUniqueFlag', ["DYNAMUSIC"]),
            window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"])
        ]);
        if (dynamicMusic == false) {
            audioSrc = ['AUDIO[mainTheme.mp3]', 'mainTheme.mp3'];
        }

        if (themeUsesIntegratedVideoAudio()) {
            releaseAudioBuffer();
            setThemeVideoAudioEnabled(shouldPlayAudio);
        } else if (!shouldPlayAudio) {
            releaseAudioBuffer();
        } else if (audioSrc?.[1] === 'mainTheme.mp3' && !theme.mainSong) {
            releaseAudioBuffer();
        } else if (audioSrc && audioSrc[1] && (audioSrc[1] !== currentAudio || !audio.src)) {
            currentAudio = audioSrc[1];
            const nextAudioSource = audioSrc[1] == 'mainTheme.mp3'
                ? themeAssetUrl(theme, 'mus', theme.mainSong)
                : './' + audioSrc[1];
            switchMenuAudioSource(nextAudioSource);

            audio.volume = TARGET_MUSIC_VOLUME;
            changeAudio = true;
        }

        if (shouldPlayAudio && !themeUsesIntegratedVideoAudio()) {
            audio.play().catch(() => {});
        }
        purifiedHTML = purifiedHTML.replace(/AUDIO\[(.*?)\]/g, '');
    }

    // Inject Viewport HTML
    const pageViewport = document.getElementsByClassName('viewport')[0];
    pageViewport.querySelectorAll('*').forEach(element => element._tippy?.destroy());
    pageViewport.querySelectorAll('img, video, source').forEach(media => {
        media.removeAttribute('src');
        media.removeAttribute('srcset');
    });
    pageViewport.dataset.page = name;
    pageViewport.innerHTML = purifiedHTML;
    window.DeltamodUI?.mount(pageViewport);
    window.Localization?.apply(pageViewport);
    window.Localization?.applyKnownText(pageViewport);

    // Set Active Sidebar Button
    ([...Array.from(document.getElementsByClassName('sidebar-button')), ...Array.from(document.getElementsByClassName('gamebanana-account'))]).forEach(button => {
        if (button.getAttribute('data-page') === (name === 'allmods-v2' ? 'allmods' : name)) {
            button.classList.add('active');
            button.setAttribute('aria-current', 'page');
        } else {
            button.classList.remove('active');
            button.removeAttribute('aria-current');
        }
    });

    // Handle Scrolling
    try {
        const vp = document.getElementsByClassName('viewport')[0];
        if (vp && typeof vp.scrollTo === 'function') {
            vp.scrollTo({ top: 0, left: 0, behavior: 'auto' });
        } else {
            window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
        }
    } catch (e) {
        window.scrollTo(0, 0);
    }

    pageN = name;

    applyThemeStyles(theme);

    // Execute Page JS
    if (runScripts) {
        try {
            await loadPageScript(pageDefinition);
        } catch (error) {
            console.error('Error occurred while loading script for page:', name, error);
        }
    }

    window.Localization?.apply(pageViewport);

    const visualTheme = activeThemeVisualConfig();
    window.ThemeSprites?.apply(visualTheme.soulColor || visualTheme.color, document)
        .then(() => {
            if (document.documentElement.classList.contains('roaring-knight-awakened')) {
                setRoaringKnightSpriteSet(true);
            }
        })
        .catch(error => {
            console.warn('Unable to recolor page sprites:', error);
        });

    if (focusContent) {
        const heading = pageViewport.querySelector('h1');
        if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); }
    }
    window.dispatchEvent(new CustomEvent('deltamod-page-ready', { detail: { name } }));
    await signalBenchmarkReadiness();

}

/**
 * ==========================================
 * Global Window Listeners
 * ==========================================
 */
function suspendApplicationMedia() {
    document.documentElement.classList.add('window-inactive');
    if (audio) {
        menuAudioWasPlayingBeforeWindowInactive = menuAudioWasPlayingBeforeWindowInactive
            || (!audio.paused && !audio.ended);
        rememberMenuAudioPosition();
        audio.pause();
        audio.volume = 0;
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo) {
        themeVideo.volume = 0;
    }
    scheduleThemeVideoSuspension();
}

async function resumeApplicationMedia() {
    clearTimeout(themeVideoSuspendTimer);
    document.documentElement.classList.remove('window-inactive');
    let shouldPlayAudio = await window.deltamodBackend.invoke('getUniqueFlag', ["AUDIO"]);
    if (audio && shouldPlayAudio) {
        audio.volume = TARGET_MUSIC_VOLUME;
        if (menuAudioWasPlayingBeforeWindowInactive && currentAudioSource) {
            await audio.play().catch(() => {});
        }
    }
    menuAudioWasPlayingBeforeWindowInactive = false;
    const resumedThemeVideo = resumeThemeBackgroundVideo(shouldPlayAudio);
    if (!resumedThemeVideo) {
        setThemeVideoAudioEnabled(shouldPlayAudio);
    }
}

window.addEventListener('blur', suspendApplicationMedia);
window.addEventListener('focus', () => {
    if (!document.hidden) void resumeApplicationMedia();
});
document.addEventListener('visibilitychange', () => {
    if (document.hidden) {
        suspendApplicationMedia();
    } else if (document.hasFocus()) {
        void resumeApplicationMedia();
    }
});

if (!window.electronAPI) {
    window.alert('This application cannot run in this environment.');
    window.close();
    window.location.href = 'about:blank';
}

var renderedUser = false;
async function renderuser() {
    if (!(await window.deltamodBackend.invoke('validateGamebananaToken')) || !navigator.onLine) {
        renderedUser = true;
        return;
    }
    var gbuser = await window.deltamodBackend.invokeOptional(
        'getGamebananaUserinfo',
        [],
        { loggedIn: false }
    );

    const ribbon = document.getElementById('collectionsRibbon');
    if (ribbon) ribbon.style.display = 'inline-flex';
    var gbaccount = document.querySelector('.gamebanana-account');
    gbaccount.replaceChildren();
    const avatar = document.createElement('img');
    const fallback = document.createElement('span');
    fallback.className = 'material-symbols-outlined gamebanana-account-fallback';
    fallback.textContent = 'account_circle';
    fallback.setAttribute('aria-hidden', 'true');
    const avatarUrl = typeof gbuser?._sAvatarUrl === 'string' ? gbuser._sAvatarUrl.trim() : '';
    avatar.src = avatarUrl;
    avatar.alt = '';
    avatar.width = 25;
    avatar.height = 25;
    avatar.style.borderRadius = '15px';
    avatar.onerror = () => {
        avatar.remove();
        if (!fallback.isConnected) gbaccount.prepend(fallback);
    };
    const username = document.createElement('span');
    username.textContent = String(gbuser?._sName || 'GameBanana user');
    username.className = 'gamebanana-account-name';
    if (avatarUrl) {
        gbaccount.append(avatar, username);
    } else {
        gbaccount.append(fallback, username);
    }
    gbaccount.style.opacity = '1';
    const openGameBananaSettings = async () => {
        if (gbaccount.getAttribute('data-disabled') === 'true') {
            return;
        }
        window._pageArguments = {
            cat: 'gb'
        };
        page('options');
    };
    gbaccount.addEventListener('click', openGameBananaSettings);
    gbaccount.addEventListener('keydown', event => {
        if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            openGameBananaSettings();
        }
    });

    renderedUser = true;
}

async function setupLanguageWheel() {
    await window.Localization.ready;

    const toggle = document.getElementById('language-wheel-toggle');
    const toggleFlag = document.getElementById('language-wheel-toggle-flag');
    const wheel = document.getElementById('language-wheel');
    const backdrop = document.getElementById('language-wheel-backdrop');
    const sectors = document.getElementById('language-wheel-sectors');
    const options = document.getElementById('language-wheel-options');
    const currentFlag = document.getElementById('language-wheel-current-flag');
    const languages = await window.Localization.getLanguages();
    const optionButtons = [];
    const sectorPaths = [];
    const wheelFlagCodes = Object.freeze({
        en: 'en',
        it: 'it',
        pl: 'pl',
        es: 'es',
        fr: 'fr',
        de: 'de',
        'pt-br': 'br',
        ja: 'jp'
    });
    const svgNamespace = 'http://www.w3.org/2000/svg';
    const sectorDefinitions = document.createElementNS(svgNamespace, 'defs');
    sectors.appendChild(sectorDefinitions);
    let closeTimer = null;
    let isChangingLanguage = false;
    let previewRotation = null;

    const selectedLanguage = () => (
        languages.find(language => language.code === window.Localization.getLanguage())
        || languages[0]
    );

    const wheelFlag = language => (
        `assets/language-flags/${wheelFlagCodes[language.code]}.svg`
    );

    const previewLanguage = language => {
        const previewIndex = Math.max(0, languages.findIndex(item => item.code === language.code));
        const targetRotation = previewIndex * (360 / languages.length);
        if (previewRotation === null) {
            previewRotation = targetRotation;
        } else {
            const currentNormalized = ((previewRotation % 360) + 360) % 360;
            const shortestDelta = (
                ((targetRotation - currentNormalized + 540) % 360) - 180
            );
            previewRotation += shortestDelta;
        }
        currentFlag.src = wheelFlag(language);
        currentFlag.alt = '';
        wheel.style.setProperty('--preview-angle', `${previewRotation}deg`);
        optionButtons.forEach(button => {
            button.classList.toggle('is-preview', button.dataset.language === language.code);
        });
        sectorPaths.forEach(path => {
            path.classList.toggle('is-preview', path.dataset.language === language.code);
        });
    };

    const syncLanguageWheel = () => {
        const language = selectedLanguage();
        toggleFlag.src = wheelFlag(language);
        previewLanguage(language);

        const changeLabel = window.Localization.t('language_switcher_label', 'Change language');
        toggle.title = changeLabel;
        toggle.setAttribute('aria-label', `${changeLabel}: ${language.name}`);
        wheel.setAttribute('aria-label', changeLabel);
        for (const button of optionButtons) {
            button.setAttribute(
                'aria-pressed',
                String(button.dataset.language === language.code)
            );
        }
        sectorPaths.forEach(path => {
            path.classList.toggle('is-current', path.dataset.language === language.code);
        });
    };

    const closeWheel = ({ returnFocus = true, restorePreview = true } = {}) => {
        if (wheel.hidden) return;
        clearTimeout(closeTimer);
        wheel.classList.remove('is-open');
        backdrop.classList.remove('is-open');
        wheel.setAttribute('aria-hidden', 'true');
        toggle.setAttribute('aria-expanded', 'false');

        const finishClose = () => {
            wheel.hidden = true;
            backdrop.hidden = true;
            if (restorePreview) previewLanguage(selectedLanguage());
            if (returnFocus) toggle.focus();
        };

        if (prefersReducedMotion()) {
            finishClose();
        } else {
            closeTimer = setTimeout(finishClose, 230);
        }
    };

    const openWheel = () => {
        clearTimeout(closeTimer);
        wheel.hidden = false;
        backdrop.hidden = false;
        wheel.setAttribute('aria-hidden', 'false');
        toggle.setAttribute('aria-expanded', 'true');
        syncLanguageWheel();

        requestAnimationFrame(() => {
            wheel.classList.add('is-open');
            backdrop.classList.add('is-open');
            const active = optionButtons.find(button => button.getAttribute('aria-pressed') === 'true');
            (active || optionButtons[0])?.focus();
        });
    };

    const focusRelativeOption = (button, direction) => {
        const currentIndex = optionButtons.indexOf(button);
        const nextIndex = (currentIndex + direction + optionButtons.length) % optionButtons.length;
        optionButtons[nextIndex].focus();
    };

    const activateLanguage = async language => {
        if (isChangingLanguage) return;
        if (language.code === window.Localization.getLanguage()) {
            closeWheel();
            return;
        }

        isChangingLanguage = true;
        previewLanguage(language);
        closeWheel({ returnFocus: false, restorePreview: false });
        try {
            await window.Localization.setLanguage(language.code);
            syncLanguageWheel();
            toggle.focus();
        } catch (error) {
            console.error(`Unable to switch language to ${language.code}:`, error);
            openWheel();
        } finally {
            isChangingLanguage = false;
        }
    };

    const polarPoint = (radius, angle) => {
        const radians = angle * (Math.PI / 180);
        return {
            x: 165 + (Math.cos(radians) * radius),
            y: 165 + (Math.sin(radians) * radius)
        };
    };

    const sectorPath = (startAngle, endAngle) => {
        const outerStart = polarPoint(157, startAngle);
        const outerEnd = polarPoint(157, endAngle);
        const innerEnd = polarPoint(68, endAngle);
        const innerStart = polarPoint(68, startAngle);
        return [
            `M ${outerStart.x} ${outerStart.y}`,
            `A 157 157 0 0 1 ${outerEnd.x} ${outerEnd.y}`,
            `L ${innerEnd.x} ${innerEnd.y}`,
            `A 68 68 0 0 0 ${innerStart.x} ${innerStart.y}`,
            'Z'
        ].join(' ');
    };

    languages.forEach((language, index) => {
        const button = document.createElement('button');
        const angle = index * (360 / languages.length);
        const buttonRadius = 112;
        const buttonAngle = (angle - 90) * (Math.PI / 180);
        const sector = document.createElementNS(svgNamespace, 'path');
        const pattern = document.createElementNS(svgNamespace, 'pattern');
        const patternImage = document.createElementNS(svgNamespace, 'image');
        const patternId = `language-sector-${language.code.replace(/[^a-z0-9]/gi, '-')}`;

        button.type = 'button';
        button.className = 'language-wheel-option noScaleBTN';
        button.dataset.language = language.code;
        button.title = language.name;
        button.setAttribute('aria-label', language.name);
        button.style.setProperty('--wheel-index', String(index));
        button.style.setProperty('--wheel-button-x', `${125 + (Math.cos(buttonAngle) * buttonRadius)}px`);
        button.style.setProperty('--wheel-button-y', `${123 + (Math.sin(buttonAngle) * buttonRadius)}px`);

        sector.classList.add('language-wheel-sector');
        sector.dataset.language = language.code;
        sector.style.fill = `url(#${patternId})`;
        sector.setAttribute('d', sectorPath(
            -112.5 + angle + 1.4,
            -67.5 + angle - 1.4
        ));

        pattern.id = patternId;
        pattern.setAttribute('width', '1');
        pattern.setAttribute('height', '1');
        pattern.setAttribute('patternUnits', 'objectBoundingBox');
        pattern.setAttribute('patternContentUnits', 'objectBoundingBox');
        patternImage.setAttribute('href', wheelFlag(language));
        patternImage.setAttribute('width', '1');
        patternImage.setAttribute('height', '1');
        patternImage.setAttribute('preserveAspectRatio', 'xMidYMid slice');
        pattern.appendChild(patternImage);
        sectorDefinitions.appendChild(pattern);
        sectors.appendChild(sector);
        sectorPaths.push(sector);

        sector.addEventListener('pointerover', () => {
            if (!isChangingLanguage) previewLanguage(language);
        });
        sector.addEventListener('click', () => activateLanguage(language));
        button.addEventListener('focus', () => previewLanguage(language));
        button.addEventListener('click', () => activateLanguage(language));
        button.addEventListener('keydown', event => {
            if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
                event.preventDefault();
                focusRelativeOption(button, 1);
            } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
                event.preventDefault();
                focusRelativeOption(button, -1);
            } else if (event.key === 'Home') {
                event.preventDefault();
                optionButtons[0].focus();
            } else if (event.key === 'End') {
                event.preventDefault();
                optionButtons[optionButtons.length - 1].focus();
            } else if (event.key === 'Escape') {
                event.preventDefault();
                closeWheel();
            }
        });

        optionButtons.push(button);
        options.appendChild(button);
    });

    toggle.addEventListener('click', () => {
        if (toggle.getAttribute('aria-expanded') === 'true') closeWheel();
        else openWheel();
    });
    wheel.addEventListener('keydown', event => {
        if (event.key !== 'Tab' || wheel.hidden) return;
        const current = optionButtons.indexOf(document.activeElement);
        if ((event.shiftKey && current <= 0) || (!event.shiftKey && (current < 0 || current === optionButtons.length - 1))) {
            event.preventDefault();
            optionButtons[event.shiftKey ? optionButtons.length - 1 : 0]?.focus();
        }
    });
    wheel.addEventListener('pointerleave', () => {
        if (!isChangingLanguage) previewLanguage(selectedLanguage());
    });
    backdrop.addEventListener('click', () => closeWheel());
    window.addEventListener('keydown', event => {
        if (event.key === 'Escape' && !wheel.hidden) {
            event.preventDefault();
            closeWheel();
        }
    });
    window.addEventListener('deltamod-language-change', syncLanguageWheel);

    syncLanguageWheel();
}

/**
 * ==========================================
 * Initialization Boot Sequence
 * ==========================================
 */
(async function() {
    bootProgress(0.03, 'Starting local runtime');
    await reapplyHAStyles();
    bootProgress(0.09, 'Loading interface styles');

    cmode = await window.deltamodBackend.invoke('isCMode', []);
    bootProgress(0.15, 'Checking controller mode');

    var ribbon = document.querySelectorAll('.sidebar-button');
    ribbon.forEach(r => {
        r.addEventListener('click', () => {
            const target = r.getAttribute('data-page');
            if (
                r.getAttribute('data-disabled') === 'true' ||
                target === pageN ||
                target === activePageNavigation ||
                target === queuedPageNavigation?.target
            ) {
                return;
            }
            page(target).catch(error => {
                console.error('Unable to navigate from the sidebar:', error);
            });
        });
    });
    
    // Initialize Theme prior to initial page loads
    await themeRefresh(false); 
    bootProgress(0.28, 'Applying active theme');
    await setupLanguageWheel();
    bootProgress(0.38, 'Preparing language services');

    // Setup Controller Mode visual adjustments
    if (cmode) {
        document.body.style.zoom = '120%';
        document.querySelector('.glyph').style.display = 'flex';
        document.querySelector('.minimize-button').style.display = 'none';
        document.querySelector('.maximize-button').style.display = 'none';

        makeGlyphs([
            { icon: 'game_stick_left', description: "Move cursor" },
            { icon: 'game_stick_right', description: "Scroll" },
            { icon: 'cancel', description: "Click" },
            { icon: 'square_circle', description: "Right click" },
        ]);

        if (!localStorage.getItem('seenCModeAlert')) {
            localStorage.setItem('seenCModeAlert', 'true');
            htmlAlert(
                "Controller mode enabled", 
                "Controller mode is now enabled! Use Deltamod with your controller. Your left stick can help you move your mouse.", 
                [{ text: "Ok" }], 
                'stadia_controller'
            );
        }
    } else {
        document.querySelector('.glyph').style.display = 'none';
        if ((await window.deltamodBackend.invoke('getOS', [])).platform != 'linux') {
            window.addEventListener("gamepadconnected", async (event) => {
                if (await window.deltamodBackend.invoke('getUniqueFlag', ["CONTROLLER"]) === false) {
                    return;
                }
                if (!event.gamepad.id.toLowerCase().includes('dualshock') && !event.gamepad.id.toLowerCase().includes('dualsense')) {
                    return;
                }
                var res = await htmlAlert(
                    "Controller mode",
                    "It looks like you have a controller connected. Do you want to enable controller mode? Controller mode allows you to use Deltamod with your controller. Your left stick can help you move your mouse.",
                    [
                        { text: "Yes", resolveWith: true },
                        { text: "No", resolveWith: false }
                    ]
                );

                if (res) {
                    await window.deltamodBackend.invoke('cmode-on', []);
                }
            });
        }
    }

    if (await offerOfficialProfileImport()) {
        bootProgress(0.7, 'Waiting for profile import');
        finishBoot();
        return;
    }

    var loaded = await window.deltamodBackend.invoke('loadedDeltarune',[]);
    bootProgress(0.56, 'Finding installed games');

    if (await window.deltamodBackend.invoke('fetchSharedVariable',["gb1click"]) === true) {
        await page('goc-dl');
        finishBoot();
        return;
    }

    bootProgress(0.72, 'Reading mod sources');

    // Main App Branching Route
    if (loaded.loaded) {
        var available = await window.deltamodBackend.invoke('fireUpdate', []);
        console.log('Update check complete. Update available:', available);
        bootProgress(0.84, 'Checking patch tools');

        var im = await invokeOptional('shouldGoIM', [], false);
        bootProgress(0.9, 'Preparing file overlay');
        if (im) {
            await page('installmanager');
        } else {
            await page('main');
        }
        finishBoot();
        (window.requestIdleCallback || (callback => setTimeout(callback, 0)))(warmPageMarkupCache);

        invokeOptional('executeArgumentCmd', [], null);
    } else {
        await page('locate');
        finishBoot();
        (window.requestIdleCallback || (callback => setTimeout(callback, 0)))(warmPageMarkupCache);
        document.querySelectorAll('.sidebar-button').forEach(button => { button.setAttribute('data-disabled', 'true'); button.setAttribute('aria-disabled', 'true'); if (button.tagName === 'BUTTON') button.disabled = true; });
        invokeOptional('executeArgumentCmd', [], null);
    }
})().catch(error => {
    console.error('Deltamod initialization failed:', error);
    window.DeltamodBoot?.fail('Unable to start');
    document.getElementById('deltamod-boot-root').hidden = true;
    document.body.classList.remove('deltamod-boot-active');
    window.DeltamodUI?.showError(document.querySelector('.viewport'), error, () => location.reload());
});

function closeAudio() {
    if (audio) {
        audio.pause();
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo) {
        themeVideo.pause();
    }
}

function openAudio() {
    if (audio && audio.src) {
        audio.play().catch(error => {
            // Silently fail if audio play is blocked
        });
    }
    const themeVideo = getThemeBackgroundVideo();
    if (themeVideo?.src) {
        themeVideo.play().catch(() => {});
    }
}

/**
 * ==========================================
 * Late Execution Modules (Shop Checker)
 * ==========================================
 */
// Account availability is optional. Network failure must not freeze local mod management.
renderuser().catch(error => {
    renderedUser = true;
    console.warn('GameBanana account is unavailable:', error);
});
